# $NetBSD: Makefile,v 1.6 2010/11/01 04:02:26 obache Exp $

DISTNAME=	oauth-0.4.4
PKGREVISION=	1
CATEGORIES=	security

MAINTAINER=	obache@NetBSD.org
HOMEPAGE=	http://oauth.rubyforge.org/
#HOMEPAGE=	http://github.com/oauth/oauth-ruby
COMMENT=	OAuth Core Ruby implementation
LICENSE=	mit

RUBYGEM_OPTIONS+=	--format-executable

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
