# $NetBSD$
#

DISTNAME=		synce-serial-0.9.1
CATEGORIES=		comms
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=synce/}

MAINTAINER=		wiz@NetBSD.org
HOMEPAGE=		http://synce.sourceforge.net/
COMMENT=		SynCE helper scripts for setting up a serial connection

USE_LIBTOOL=		yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
