# $NetBSD$
#
# Makefile fragment to build a static libperl.a to be appended to the perl
# Makefile after the configure process.  This is copied from Makefile.SH.

LIBPERL_STATIC=	libperl.a

libperl.a: $& perl$(OBJ_EXT) $(obj) $(LIBPERLEXPORT)
	rm -f $(LIBPERL_STATIC)
	$(AR) rcu $(LIBPERL_STATIC) perl$(OBJ_EXT) $(obj)
	@$(ranlib) $(LIBPERL_STATIC)
