# $NetBSD: Makefile,v 1.4 2009/03/18 18:20:36 darcy Exp $

DISTNAME=	fcrackzip-1.0
MASTER_SITES=	http://home.schmorp.de/marc/data/
CATEGORIES=	archivers

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://home.schmorp.de/marc/fcrackzip.html
COMMENT=	Zip password cracker

LICENSE=	gnu-gpl-v2

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes

CONFLICTS=	unzip-[0-9]*

.include "../../mk/bsd.pkg.mk"
