# $NetBSD: Makefile,v 1.2 2004/05/04 04:26:43 snj Exp $
.include "Makefile.common"

COMMENT=		Flash Player plugin for firefox-bin

DEPENDS+=		firefox-bin>=0.8:../../www/firefox-bin

.include "../../emulators/suse_linux/Makefile.application"
.include "../../mk/bsd.pkg.mk"
