# $NetBSD: Makefile.version,v 1.7 2003/09/08 04:47:51 epg Exp $

.if !defined(SVNVER)
SVNVER=		0.30.0
# This macro is in this file because the URL changes with every release.
MASTER_SITES=	http://svn.collab.net/tarballs/
.endif
