# $NetBSD$
#

DISTNAME=		Tempita-0.4
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
EGG_NAME=		${DISTNAME}
CATEGORIES=		textproc python
MASTER_SITES=		http://pypi.python.org/packages/source/T/Tempita/

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://pythonpaste.org/tempita/
COMMENT=		Small Python templating language
LICENSE=		mit

PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
