# $NetBSD: Makefile,v 1.2 2010/05/19 22:59:13 minskim Exp $

DISTNAME=	amsrefs.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.09
TEXLIVE_REV=	20249

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-amsrefs

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
