# $NetBSD: Makefile,v 1.1.1.1 2010/04/29 22:53:45 minskim Exp $

DISTNAME=	ulem
PKGNAME=	tex-${DISTNAME}-2010
TEXLIVE_REV=	20083

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Package for underlining

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
