# $NetBSD$
# TeX Live Revision 16866

DISTNAME=	ulem
PKGNAME=	tex-${DISTNAME}-2009

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Package for underlining

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
