# $NetBSD$

VERSION=	20071029
DISTNAME=	ga_IE
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Irish dictionary for hunspell

.include "../../textproc/hunspell/Makefile.common"

.include "../../mk/bsd.pkg.mk"
