# $NetBSD: Makefile,v 1.3 1998/01/24 21:02:40 hubertf Exp $
# FreeBSD Id: Makefile,v 1.2 1996/11/11 05:49:31 obrien Exp
#

DISTNAME=	fep
PKGNAME=	fep-1.0
CATEGORIES=	misc
MASTER_SITES=	ftp://ftp.sra.co.jp/pub/cmd/

MAINTAINER=	nobu@psrc.isac.co.jp

NO_WRKSUBDIR=	yes
MANCOMPRESSED=	yes
MAN1=		fep.1

.include "../../mk/bsd.pkg.mk"
