# $NetBSD: Makefile,v 1.1.1.1 2010/04/09 21:47:13 markd Exp $

DISTNAME=	polytable
PKGNAME=	tex-${DISTNAME}-0.8.2
PKGREVISION=	1
TEXLIVE_REV=	20331

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Tabular-like environments with named columns

DEPENDS+=	tex-latex-bin>=2009nb1:../../print/tex-latex-bin
DEPENDS+=	tex-lazylist>=1.0a:../../print/tex-lazylist
DEPENDS+=	tex-tools>=2010:../../print/tex-tools

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
