# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TAGLIB_BUILDLINK3_MK:=	${TAGLIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	taglib
.endif

.if !empty(TAGLIB_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=			taglib
BUILDLINK_DEPENDS.taglib?=		taglib>=1.0
BUILDLINK_PKGSRCDIR.taglib?=		../../audio/TagLib

.endif # TAGLIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
