# $NetBSD$

DISTNAME=	picinpar.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.2a
TEXLIVE_REV=	20374

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-picinpar

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
