# $NetBSD$

DISTNAME=	flexmock-0.8.0
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://flexmock.rubyforge.org/
COMMENT=	Flexible mock object library for Ruby unit testing

.include "../../misc/rubygems/rubygem.mk"
.include "../../mk/bsd.pkg.mk"
