# $NetBSD: Makefile,v 1.1.1.1 2009/04/30 05:06:10 minskim Exp $
# TeX Live Revision 15878

DISTNAME=	symbol
PKGNAME=	tex-${DISTNAME}-2008.7340
DIST_SUBDIR=	${PKGBASE}-15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Symbol fonts for TeX

CONFLICTS+=	teTeX-texmf<=3.0nb14

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
