# $NetBSD$

DISTNAME=	esound-0.2.15
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_GNOME:=gnome-1.0.53/sources/}

MAINTAINER=	root@garbled.net
HOMEPAGE=	http://pw1.netcom.com/~ericmit/EsounD.html

DEPENDS+=	libaudiofile-*:../../audio/libaudiofile

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_LIBTOOL=	yes

.include "../../mk/bsd.pkg.mk"
