# $NetBSD: Makefile,v 1.6 1999/06/19 15:19:11 tron Exp $

DISTNAME=	esound-0.2.8
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_GNOME:=gnome-1.0/sources/}

MAINTAINER=	root@garbled.net
HOMEPAGE=	http://pw1.netcom.com/~ericmit/EsounD.html

DEPENDS+=	libaudiofile-0.1.6:../../audio/libaudiofile

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_LIBTOOL=	yes

.include "../../mk/bsd.pkg.mk"
