# $NetBSD: Makefile,v 1.1.1.1 2001/01/15 06:40:23 itojun Exp $

DISTNAME=	scanssh-1.3a
CATEGORIES=	security
MASTER_SITES=	http://www.monkey.org/~provos/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.monkey.org/~provos/scanssh/
COMMENT=	ssh remote version scanner

GNU_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/scanssh

.include "../../mk/bsd.pkg.mk"
