# $NetBSD$
# TeX Live Revision 11896

DISTNAME=	metafont
PKGNAME=	tex-${DISTNAME}-2008.11896
CATEGORIES=	fonts

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Files for METAFONT

CONFLICTS+=	teTeX-texmf<=3.0nb13

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
