# $NetBSD: Makefile,v 1.2 2000/08/12 06:34:36 jlam Exp $

PKGNAME=		${DISTNAME:S/-/-share-/}

CONFIGURE_ARGS+=	--disable-server
CONFIGURE_ARGS+=	--enable-client=no

.include "../../games/freeciv-share/Makefile.common"
