# $NetBSD: Makefile,v 1.1.1.1 2009/07/09 23:09:17 minskim Exp $

DISTNAME=	moreverb.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.3
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-moreverb

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
