# $NetBSD: Makefile,v 1.3 2010/09/14 00:18:17 minskim Exp $

DISTNAME=	moreverb.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.3a
TEXLIVE_REV=	22126

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-moreverb

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
