# $NetBSD$

DISTNAME=	ccache-1.5
MASTER_SITES=	http://ccache.samba.org/ftp/ccache/
CATEGORIES=	devel
MAINTENER=	packages@netbsd.org
HOMEPAGE=	http://ccache.samba.org/
COMMENT=	Cache for C/C++ compilers

GNU_CONFIGURE=

.include "../../mk/bsd.pkg.mk"
