# $NetBSD: Makefile,v 1.1.1.1 2010/04/27 18:34:31 minskim Exp $

DISTNAME=	framed
PKGNAME=	tex-${DISTNAME}-0.95
TEXLIVE_REV=	17274

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Framed or shaded regions that can break across pages

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
