# $NetBSD$
# TeX Live Revision 9303

DISTNAME=	acmconf.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.3

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-acmconf

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
