# $NetBSD: Makefile,v 1.2 1999/03/07 00:37:19 kim Exp $

DISTNAME=	remind-03.00.19
PKGNAME=	${DISTNAME:C/0([0-9])/\1/g}
CATEGORIES=	misc
MASTER_SITES=	ftp://ftp.doe.carleton.ca/pub/remind-3.0/
EXTRACT_SUFX=	.tgz

MAINTAINER=	kim@tac.nyc.ny.us

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
