# $NetBSD$

DISTNAME=	remind-03.00.19
PKGNAME!=	echo ${DISTNAME} | sed -e 's/0\([0-9]\)/\1/g'
CATEGORIES=	misc
MASTER_SITES=	ftp://ftp.doe.carleton.ca/pub/remind-3.0/
EXTRACT_SUFX=	.tgz

MAINTAINER=	kim@tac.nyc.ny.us

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
