# $NetBSD$
# TeX Live Revision 7340

DISTNAME=	helvetic
PKGNAME=	tex-${DISTNAME}-2008.7340

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Adobe Helvetica fonts

CONFLICTS+=	teTeX-texmf<=3.0nb19

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
