# $NetBSD: Makefile,v 1.1.1.1 2009/07/15 21:00:18 minskim Exp $
# TeX Live Revision 16767

DISTNAME=	helvetic
PKGNAME=	tex-${DISTNAME}-2009

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Adobe Helvetica fonts

CONFLICTS+=	teTeX-texmf<=3.0nb19

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
