# $NetBSD: Makefile,v 1.4 2001/12/16 18:30:14 augustss Exp $
#

DISTNAME=       birda-0.4
CATEGORIES=	comms
MASTER_SITES=   ftp://ftp.augustsson.net/pub/netbsd/

MAINTAINER=	lennart@augustsson.net
COMMENT=	Bohlin's IrDA utilities

.include "../../mk/bsd.pkg.mk"
