# $NetBSD: Makefile,v 1.2 2001/12/05 16:58:56 augustss Exp $
#

DISTNAME=       birda-0.2
CATEGORIES=	comms
MASTER_SITES=   ftp://ftp.augustsson.net/pub/netbsd/

ONLY_FOR_PLATFORM=	NetBSD-1.5Z-* NetBSD-1.5Z[A-Z]-* NetBSD-1.[6-9]*-*
MAINTAINER=	lennart@augustsson.net
COMMENT=	Bohlin's IrDA utilities

.include "../../mk/bsd.pkg.mk"
