# $NetBSD: Makefile,v 1.15 2005/11/14 12:33:23 augustss Exp $
#

DISTNAME=       birda-1.3
CATEGORIES=	comms
MASTER_SITES=   ftp://ftp.augustsson.net/pub/netbsd/

MAINTAINER=	lennart@augustsson.net
COMMENT=	Bohlin's IrDA utilities

MAKE_ENV+=		BINOWN=${BINOWN} BINGRP=${BINGRP} BINMODE=${BINMODE}
MAKE_ENV+=		MANOWN=${MANOWN} MANGRP=${MANGRP} MANMODE=${MANMODE}

.include "../../mk/bsd.pkg.mk"
