# $NetBSD$
#

DISTNAME=	freezetag-0.9.2
CATEGORIES=	audio
MASTER_SITES=	http://katz.linuxpower.org/freezetag/current/

MAINTAINER=	kleink@netbsd.org
HOMEPAGE=	http://katz.linuxpower.org/freezetag/

DEPENDS=	gtk+-1.2.2:../../x11/gtk

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
