# $NetBSD: Makefile,v 1.3 2010/12/04 04:13:50 taca Exp $

DISTNAME=	addressable-2.2.6
CATEGORIES=	net

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://addressable.rubyforge.org/
COMMENT=	Replacement for the URI Implementation of standard librrary
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
