#!/bin/sh
#
# $NetBSD$

TEXMF=@PREFIX@/share/texmf
TEXMFLOCAL=@PREFIX@/share/texmf.local
PSTRICKS=$TEXMF/dvips/pstricks

case $STAGE in
PRE-INSTALL)
	;;

POST-INSTALL)
	$MV $TEXMF/web2c/texmf.cnf $TEXMF/web2c/texmf.cnf.orig
	$LN -s $TEXMFLOCAL/web2c/texmf.cnf $TEXMF/web2c/texmf.cnf
	@PATCH@ -d $PSTRICKS < $PSTRICKS/PSTricks.patch
	@PREFIX@/bin/mktexlsr
	;;

*)
	$ECHO "Unexpected argument: $STAGE"
	exit 1
	;;

esac
