# $NetBSD: Makefile,v 1.1.1.1 1999/11/06 16:50:47 wennmach Exp $
#

DISTNAME=	cgilib-0.5
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.infodrom.north.de/pub/people/joey/cgilib/

MAINTAINER=	wulf@ping.net.au
HOMEPAGE=	http://www.infodrom.north.de/cgilib/
COMMENT=	Common gateway interface library

BUILD_DEPENDS+= rman:../../textproc/rman

.include "../../mk/bsd.pkg.mk"
