# $NetBSD: Makefile,v 1.9 2004/10/03 00:18:25 tv Exp $
#

DISTNAME=	cgilib-0.5
PKGREVISION=	3
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.infodrom.north.de/pub/people/joey/cgilib/

MAINTAINER=	wulf@ping.net.au
HOMEPAGE=	http://www.infodrom.north.de/cgilib/
COMMENT=	Common gateway interface library

USE_BUILDLINK3=	yes
USE_LIBTOOL=	yes

.include "../../mk/bsd.pkg.mk"
