#! /bin/sh
#
# $NetBSD: INSTALL,v 1.3 1999/08/17 23:33:49 tron Exp $
#

case $2 in
    PRE-INSTALL)
        ;;
    POST-INSTALL)
	cat <<EOT
---------------------------------------------------------------------------
You may consider running ${PKG_PREFIX}/bin/texconfig to adjust for your
local environment, e.g. configure font generation to use a temporary
directory.

For further information have a look at ${PKG_PREFIX}/share/texmf/doc/tetex/.
---------------------------------------------------------------------------
EOT
	;;
    *)
	echo "Unexpected Argument $2!!"
	exit 1
	;;
esac

exit 0
