# $NetBSD: Makefile,v 1.3 2008/09/15 15:32:00 taca Exp $

DISTNAME=		facter-1.5.2
PKGNAME=		${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=		sysutils

MAINTAINER=		tonnerre@NetBSD.org
HOMEPAGE=		http://www.reductivelabs.com/projects/facter/
MASTER_SITE=		http://reductivelabs.com/downloads/gems/
COMMENT=		Cross-platform Ruby library for retrieving facts from OS

GEM_BUILD=		gemspec

.include "../../misc/rubygems/rubygem.mk"
.include "../../mk/bsd.pkg.mk"
