# $NetBSD$

DISTNAME=	epsf.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.7.3
TEXLIVE_REV=	17190

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-epsf

CONFLICTS+=	teTeX-texmf<=3.0nb25

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
