# $NetBSD: Makefile,v 1.3 2008/10/06 01:04:29 minskim Exp $

PKGNAME=		${CLEARSILVER_BASE}

PKG_INSTALLATION_TYPES=	overwrite pkgviews
PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../www/clearsilver/Makefile.common"

.include "../../mk/bsd.pkg.mk"
