# $NetBSD: Makefile,v 1.1.1.1 2004/11/28 23:59:40 epg Exp $

PKGNAME=		${CLEARSILVER_BASE}
PKGREVISION=		1

.include "../../www/clearsilver/Makefile.common"

PKG_INSTALLATION_TYPES=	overwrite pkgviews

.include "../../mk/bsd.pkg.mk"
