# $NetBSD$

DISTNAME=	nolbreaks
PKGNAME=	tex-${DISTNAME}-1.0
TEXLIVE_REV=	18127

MAINTAINER=	minskim@NetBSD.org
COMMENT=	No line breaks in text

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
