# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SDLMM_BUILDLINK3_MK:=	${SDLMM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	SDLmm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NSDLmm}
BUILDLINK_PACKAGES+=	SDLmm

.if !empty(SDLMM_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.SDLmm+=	SDLmm>=0.1.8nb1
BUILDLINK_PKGSRCDIR.SDLmm?=	../../devel/SDLmm

.include "../../devel/SDL/buildlink3.mk"

.endif	# SDLMM_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
