# $NetBSD$

DISTNAME=	merb-cache-0.9.2
CATEGORIES=	www

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.merbivore.com/
COMMENT=	Merb plugin that provides caching (page, action, fragment, object)

DEPENDS+=	merb-core>=0.9.2:../../www/merb-core

.include "../../misc/rubygems/rubygem.mk"
.include "../../mk/bsd.pkg.mk"
