# $NetBSD$

R_PKGNAME=	boot
R_PKGVER=	1.2-8

MAINTAINER=	markd@netbsd.org
COMMENT=	Bootstrap R (S-Plus) Functions (Canty)

PLIST_SRC=	/dev/null

R_DEPENDS=	R>=1.5.0

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
