# $NetBSD: Makefile,v 1.2 2005/12/31 12:32:31 wiz Exp $
#

GST_PLUGINS0.8_NAME=	esound
GST_PLUGINS0.8_DIR=	ext/esd
GST_PLUGINS0.8_FLAG=	esd

.include "../../multimedia/gst-plugins0.8/Makefile.common"

.include "../../audio/esound/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
