# $NetBSD: Makefile,v 1.19 2000/06/08 23:33:39 jlam Exp $
#

DISTNAME=		pilot-link.0.9.3
PKGNAME=		pilot-link-0.9.3
CATEGORIES=		comms
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=pilot-link/}

MAINTAINER=		sommerfeld@alum.mit.edu
HOMEPAGE=		http://www.sourceforge.net/projects/pilot-link/

USE_PERL5=		# defined
GNU_CONFIGURE=		# defined

USE_LIBTOOL=		# defined
LTCONFIG_OVERRIDE=	${WRKSRC}/scripts/ltconfig

.include "../../mk/bsd.pkg.mk"
