# $NetBSD: Makefile,v 1.9 1998/07/04 09:19:03 mycroft Exp $
# FreeBSD: Makefile,v 1.3 1997/08/26 07:12:20 tg Exp
#

DISTNAME=		xbmbrowser5.1
PKGNAME=		xbmbrowser-5.1
CATEGORIES=		graphics
MASTER_SITES=		${MASTER_SITE_XCONTRIB:=utilities/}

MAINTAINER=		packages@netbsd.org

USE_IMAKE=		YES
USE_GMAKE=		YES
USE_XPM=		YES

.include "../../mk/bsd.pkg.mk"
