# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/02/06 07:08:11 bjs Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY_BOTO_BUILDLINK3_MK:=		${PY_BOTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	py-boto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npy-boto}
BUILDLINK_PACKAGES+=	py-boto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}py-boto

.if ${PY_BOTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.py-boto+=	${PYPKGPREFIX}-boto>=1.0a
BUILDLINK_PKGSRCDIR.py-boto?=	../../net/py-boto
.endif	# PY_BOTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
