# $NetBSD: Makefile,v 1.2 1999/08/14 22:16:54 tron Exp $

DISTNAME=	xjewel-1.6
CATEGORIES=	games x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB:S/contrib/R5contrib/}
EXTRACT_SUFX=	.tar.z

MAINTAINER=	jdc@netbsd.org

USE_IMAKE=	yes

.include "../../mk/bsd.pkg.mk"
