# $NetBSD$

DISTNAME=	pciutils-2.1.11
CATEGORIES=	sysutils
MASTER_SITES=	ftp://atrey.karlin.mff.cuni.cz/pub/linux/pci/ \
		ftp://ftp.kernel.org/pub/software/utils/pciutils/ \
		ftp://metalab.unc.edu/pub/Linux/hardware/

MAINTAINER=	cube@cubidou.net
HOMEPAGE=	http://atrey.karlin.mff.cuni.cz/~mj/pciutils.shtml
COMMENT=	PCI bus manipulation utility similar to NetBSD pcictl(8)

USE_GMAKE=	YES

.include "../../mk/bsd.pkg.mk"
