# $NetBSD: Makefile,v 1.3 2001/02/16 15:22:30 wiz Exp $
#

DISTNAME=	photopc-3.04
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=photopc/}

MAINTAINER=	hubertf@netbsd.org
HOMEPAGE=	http://photopc.sourceforge.net/
COMMENT=	Manipulate digital still cameras

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
