# $NetBSD$

DISTNAME=	cmsd
PKGNAME=	tex-${DISTNAME}-2010
TEXLIVE_REV=	18787

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Interfaces to the CM Sans Serif Bold fonts

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
