# $NetBSD: Makefile,v 1.1.1.1 2000/05/12 20:40:18 sakamoto Exp $
#

DISTNAME=	chsfont
CATEGORIES=	fonts

COMMENT=	Asian Font Packs for Acrobat Reader 4.0 (Chinese Simplified)

DEPENDS+=	acroread-font-share-4.0:../../fonts/acroread-font-share

WRKSRC=		${WRKDIR}/CHSKIT
TAR_FILE=	${WRKSRC}/LANGCHS.TAR

.include "../acroread-font-share/Makefile.common"
