# $NetBSD$
#

DISTNAME=	xclip-0.08
CATEGORIES=	x11
MASTER_SITES=	http://people.debian.org/~kims/xclip/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://people.debian.org/~kims/xclip/
COMMENT=	Command line interface to the X windows clipboard

WRKSRC=		${WRKDIR}/xclip
USE_IMAKE=	YES

.include "../../mk/bsd.pkg.mk"
