# $NetBSD$

DISTNAME=	tex-gyre.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.004
TEXLIVE_REV=	18651

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-tex-gyre

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
