#	$NetBSD: Makefile,v 1.1.1.1 2010/01/17 01:33:25 dholland Exp $

all depend clean distclean:
	(cd mkhits && $(MAKE) $@)
	(cd mkastosc && $(MAKE) $@)
	(cd mkastods && $(MAKE) $@)
	(cd mkdstoas && $(MAKE) $@)
	(cd mkdctype && $(MAKE) $@)
	(cd mkmake && $(MAKE) $@)
	(cd prt3270 && $(MAKE) $@)
