# $NetBSD: Makefile,v 1.5 2006/09/24 16:42:56 salo Exp $

MOZILLA=	firefox

HOMEPAGE=	http://www.mozilla.org/projects/firefox/
COMMENT=	Lightweight gecko-based web browser (nightly binary pkg)

EMUL_PLATFORMS=		linux-i386
EMUL_PLATFORMS+=	solaris-i386 solaris-sparc

.include "../../www/seamonkey-bin-nightly/Makefile.common"
