#! /bin/sh
#
# $NetBSD: canna,v 1.2 2002/06/10 09:47:28 sakamoto Exp $
#
# PROVIDE: canna
# REQUIRE: DAEMON

if [ -f /etc/rc.subr ]
then
	. /etc/rc.subr
fi

name="canna"
rcvar=$name
command="@PREFIX@/sbin/cannaserver"
stop_cmd="@PREFIX@/bin/cannakill"

if [ -f /etc/rc.subr -a -d /etc/rc.d -a -f /etc/rc.d/DAEMON ]
then
	load_rc_config $name
	run_rc_command "$1"
else
	@ECHO@ -n ' ${name}'
	${command} ${canna_flags} ${command_args}
fi
