# $NetBSD: Makefile.common,v 1.5 2004/11/27 15:39:17 taca Exp $

RUBY_DBI_DISTNAME=	dbi-${RUBY_DBI_VERSION}
RUBY_DBI_MASTER_SITES=	http://rubyforge.org/frs/download.php/8655/
RUBY_DBI_HOMEPAGE=	http://ruby-dbi.rubyforge.org/

RUBY_DBI_VERSION=	0.1.0
