# $NetBSD: Makefile,v 1.26 2004/06/15 14:26:34 grant Exp $
#

PKGNAME=	python23-nth-2.3.4

CONFIGURE_ARGS+=        --without-threads

PY_VER_SUFFIX=	2n3

.include "../../lang/python23/Makefile.common"
