# $NetBSD$
# TeX Live Revision 17093

DISTNAME=	beamer.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-3.07

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Documentation for tex-beamer

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
