# $NetBSD$
#

DISTNAME=       XmHTML-1.1.5
CATEGORIES=	x11
MASTER_SITES=   http://www.xs4all.nl/~ripley/XmHTML/dist/

MAINTAINER=	mellon@isc.org
HOMEPAGE=	http://www.xs4all.nl/~ripley/XmHTML/

USE_LOCALBASE_FOR_X11=
USE_IMAKE=      yes

.include "../../mk/bsd.pkg.mk"
