# $NetBSD: Makefile,v 1.3 1998/04/15 10:38:07 agc Exp $
# FreeBSD Id: Makefile,v 1.3 1996/11/18 11:20:59 asami Exp 
#

DISTNAME=       freeze-2.5
CATEGORIES=	archivers
MASTER_SITES=	ftp://lupin.csv.warwick.ac.uk/pub/compression/

MAINTAINER=     lukin@okbmei.msk.su

GNU_CONFIGURE=	yes
ALL_TARGET=	prog

.include "../../mk/bsd.pkg.mk"
