# $NetBSD: Makefile,v 1.8 2000/02/25 01:04:14 wiz Exp $
#

    SUBDIR += imm
    SUBDIR += nte
    SUBDIR += rat
    SUBDIR += sdr
    SUBDIR += vat
    SUBDIR += vic

.include "../mk/bsd.pkg.subdir.mk"
