# $NetBSD: Makefile,v 1.2 2001/02/17 17:21:57 wiz Exp $

DISTNAME=	asp2php-0.75.24
CATEGORIES=	www
MASTER_SITES=	http://home.swbell.net/mikekohn/asp2php/

MAINTAINER=	shell@shellhung.org
HOMEPAGE=	http://asp2php.naken.cc/
COMMENT=	converts asp pages to php pages

WRKSRC=		${WRKDIR}/asp2php

.include "../../mk/bsd.pkg.mk"
