#	$NetBSD$
#
# Created with "make makesfiles"
# Do not edit this file manually!
#
SFILES+=	content-types.properties
SFILES+=	flavormap.properties
SFILES+=	fontconfig.bfc
SFILES+=	fontconfig.properties.src
SFILES+=	i386/jvm.cfg
SFILES+=	images/cursors/cursors.properties
SFILES+=	logging.properties
SFILES+=	management/management.properties
SFILES+=	net.properties
SFILES+=	psfont.properties.ja
SFILES+=	psfontj2d.properties
SFILES+=	security/java.security
SFILES+=	sound.properties
