# $NetBSD: Makefile,v 1.6 2006/08/03 09:37:35 ghen Exp $

MOZILLA=		seamonkey-gtk1
COMMENT=		Full featured gecko-based browser built with GTK1

.include "../../www/seamonkey/Makefile.common"
.include "../../mk/bsd.pkg.mk"
