# $NetBSD$
# TeX Live Revision 7340

DISTNAME=	sectsty
PKGNAME=	tex-${DISTNAME}-2.0.2

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Control sectional headers

CONFLICTS+=	teTeX-texmf<=3.0nb17

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
