# $NetBSD: Makefile,v 1.4 2002/01/19 08:38:41 taca Exp $
#

DISTNAME=	wmfishtime-1.23
CATEGORIES=	time x11
MASTER_SITES=	http://www.ne.jp/asahi/linux/timecop/software/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.ne.jp/asahi/linux/timecop/
COMMENT=	dockable clock application with clock, date and fish

USE_X11BASE=	# defined
USE_BUILDLINK2=	# defined

.include "../../x11/gtk/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
