# $NetBSD$
#

DISTNAME=	id3ed-1.6
CATEGORIES=	audio
MASTER_SITES=	http://www.azstarnet.com/~donut/id3ed/

MAINTAINER=	hubertf@netbsd.org
HOMEPAGE=	http://www.azstarnet.com/~donut/programs.html

DEPENDS+=	readline-2.2:../../devel/readline

USE_GMAKE=	YES
WRKSRC=		${WRKDIR}/id3ed

.include "../../mk/bsd.pkg.mk"
