# $NetBSD$

.ifndef XORG_FONTSENCODINGS_COMMON
XORG_FONTSENCODINGS_COMMON=	defined

BUILD_DEPENDS+=	xorg-clients>=${XORG_VER}:../../x11/xorg-clients

FILESDIR=	${PKGSRCDIR}/fonts/xorg-fontsEncodings/files
PATCHDIR=	${PKGSRCDIR}/fonts/xorg-fontsEncodings/patches
DISTINFO_FILE=	${PKGSRCDIR}/fonts/xorg-fontsEncodings/distinfo

.include "../../meta-pkgs/xorg/Makefile.common"

.endif
