# $NetBSD: buildlink3.mk,v 1.11 2009/03/20 17:30:10 joerg Exp $

BUILDLINK_TREE+=	pyZODB

.if !defined(PY_ZODB_BUILDLINK3_MK)
PY_ZODB_BUILDLINK3_MK:=

.include "../../lang/python/pyversion.mk"

BUILDLINK_API_DEPENDS.pyZODB+=	${PYPKGPREFIX}-ZODB>=3.2nb1
BUILDLINK_ABI_DEPENDS.pyZODB+=	${PYPKGPREFIX}-ZODB>=3.2.1nb2
BUILDLINK_PKGSRCDIR.pyZODB?=	../../databases/py-ZODB
.endif # PY_ZODB_BUILDLINK3_MK

BUILDLINK_TREE+=	-pyZODB
