# $NetBSD: buildlink3.mk,v 1.22 2004/02/18 16:35:27 jlam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLU_BUILDLINK3_MK:=	${GLU_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glu
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglu}
BUILDLINK_PACKAGES+=	glu

.if !empty(GLU_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.glu+=		glu>=${_MESA_REQD}
BUILDLINK_PKGSRCDIR.glu?=	../../graphics/glu

.include "../../graphics/MesaLib/buildlink3.mk"

.endif	# GLU_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
