# $NetBSD: Makefile,v 1.1.1.1 2006/04/08 11:44:28 jmmv Exp $
#

GST_PLUGINS0.10_NAME=	a52
GST_PLUGINS0.10_DIRS=	ext/a52dec

.include "../../multimedia/gst-plugins0.10-ugly/Makefile.common"

.include "../../audio/liba52/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
