# $NetBSD$
#

DISTNAME=	users-guide-1.0.71
PKGNAME=	gnome-users-guide-1.0.71
CATEGORIES=	x11 gnome
MASTER_SITES=	${MASTER_SITE_GNOME:=sources/users-guide/}

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.gnome.org/users-guide/project.shtml

GNU_CONFIGURE=	YES
USE_X11BASE=	YES

.include "../../mk/bsd.pkg.mk"
