# $NetBSD: Makefile,v 1.4 2007/09/08 21:58:00 jlam Exp $

USE_FEATURES=	nbcompat
PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../pkgtools/mtree/Makefile.common"

CATEGORIES=	sysutils

.include "../../mk/bsd.pkg.mk"
