# $NetBSD: Makefile,v 1.3 2005/12/29 11:12:15 markd Exp $
#

DISTNAME=	chtfont
PKGREVISION=	1
CATEGORIES=	fonts

MAINTAINER=	tech-pkg@NetBSD.org
COMMENT=	Asian Font Packs for Acrobat Reader 7 (Chinese Traditional)

DEPENDS+=	acroread7-font-share-7.0nb1:../../fonts/acroread7-font-share

WRKSRC=		${WRKDIR}/CHTKIT
TAR_FILE=	${WRKSRC}/LANGCHT.TAR

.include "../../fonts/acroread7-font-share/Makefile.common"
