#!/bin/sh
#
# $NetBSD$
#

PKGNAME=$1

case $2 in
DEINSTALL)
	;;
POST-DEINSTALL)
	cat << EOF
=============================================================================
If you won't be using ${PKGNAME} any longer, you may want to remove the
score file ${PKG_PREFIX}/var/gtkballs-scores.
=============================================================================
EOF
	;;
*)
	echo "Unexpected argument: $2"
	exit 1
	;;
esac
exit 0
