# $NetBSD$
# FreeBSD Id: ports/misc/rtfm/Makefile,v 1.10 2001/01/16 17:31:43 sobomax Exp

DISTNAME=	rtfm-1.0
CATEGORIES=	textproc
MASTER_SITES=	ftp://ftp.freebsd.org/pub/FreeBSD/ports/distfiles/ \
		ftp://ftp.pl.freebsd.org/pub/FreeBSD/ports/distfiles/

MAINTAINER=	zuntum@eik.pl

.include "../../mk/bsd.pkg.mk"
