# $NetBSD: Makefile,v 1.45 2000/06/03 19:07:29 fredb Exp $
#

COMMENT=	Screen saver and locker for the X window system

CONFLICTS+=	xscreensaver-gnome-[0-9]*

CONFIGURE_ARGS+=--without-gnome

.include "../../x11/xscreensaver/Makefile.common"
