# $NetBSD: buildlink3.mk,v 1.8 2006/07/08 23:11:11 jlam Exp $

BUILDLINK_TREE+=	${RUBY_PKGPREFIX}-eruby

.if !defined(RUBY_ERUBY_BUILDLINK3_MK)
RUBY_ERUBY_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.ruby18-eruby+=	${RUBY_PKGPREFIX}-eruby>=0.9.7
BUILDLINK_PKGSRCDIR.ruby18-eruby?=	../../textproc/ruby-eruby
.endif # RUBY_ERUBY_BUILDLINK3_MK

BUILDLINK_TREE+=	-${RUBY_PKGPREFIX}-eruby
