# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
RUBY_ERUBY_BUILDLINK3_MK:=	${RUBY_ERUBY_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ruby-eruby
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nruby-eruby}
BUILDLINK_PACKAGES+=	ruby-eruby

.if !empty(RUBY_ERUBY_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.ruby-eruby+=	ruby-eruby>=0.9.7
BUILDLINK_PKGSRCDIR.ruby-eruby?=	../../textproc/ruby-eruby
.endif	# RUBY_ERUBY_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
