# $NetBSD: Makefile,v 1.3 2005/12/26 23:39:32 schmonz Exp $

PKGNAME=	jdk-openjit-${OPENJIT_VERSION}

BROKEN_IN=	pkgsrc-2005Q4

PKG_JVMS_ACCEPTED= jdk
CLASSDIR=	classes
JRELIB=		lib/${MACHINE_ARCH}/green_threads

.include "../../lang/jdk-openjit/Makefile.common"
