# $NetBSD$
# TeX Live Revision 9734

DISTNAME=	exam.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.3

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-exam

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
