# $NetBSD: Makefile,v 1.5 2006/02/05 23:10:29 joerg Exp $

DISTNAME=	Net_URL-1.0.14
CATEGORIES+=	net

MAINTAINER=	jdolecek@NetBSD.org
COMMENT=	PHP classes to easy parsing of URLs

CONFLICTS=	php-pear-Net_URL-[0-9]

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
