# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
P5_POE_BUILDLINK3_MK:=	${P5_POE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	p5-POE
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Np5-POE}
BUILDLINK_PACKAGES+=	p5-POE

.if !empty(P5_POE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.p5-POE+=	p5-POE>=0.3101nb1
BUILDLINK_PKGSRCDIR.p5-POE?=	../../devel/p5-POE
.endif	# P5_POE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
