#!/bin/sh
#
# $NetBSD$
#
REALPLAYER_HOME=@@REALPLAYER_HOME@@ ; export REALPLAYER_HOME
LD_LIBRARY_PATH=${REALPLAYER_HOME}:${LD_LIBRARY_PATH} ; export LD_LIBRARY_PATH
exec ${REALPLAYER_HOME}/realplay "$@"
