# $NetBSD$
# TeX Live Revision 17670

DISTNAME=	pgfplots.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.2.2

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Documentation for tex-pgfplots

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
