# $NetBSD$
# TeX Live Revision 17262

DISTNAME=	excludeonly.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.0

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-excludeonly

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
