# $NetBSD: Makefile,v 1.1.1.1 2007/12/12 18:01:34 adam Exp $

KOFFICE_LANGUAGE=	Polish
KOFFICE_LANGCODE=       pl

PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../misc/koffice/l10n.mk"
.include "../../mk/bsd.pkg.mk"
