# $NetBSD: Makefile,v 1.6 2001/09/30 05:11:58 itojun Exp $

DISTNAME=	magicpoint-1.09a
PKGNAME=	xmindpath-1.09a
WRKSRC=		${WRKDIR}/${DISTNAME}/contrib/xmindpath
CATEGORIES=	x11
MASTER_SITES=	ftp://ftp.mew.org/pub/MagicPoint/

MAINTAINER=	itojun@itojun.org
COMMENT=	MindPath PocketPoint user-level driver for X11

GNU_CONFIGURE=	yes
USE_X11=	yes

.include "../../mk/bsd.pkg.mk"
