# $NetBSD: Makefile,v 1.4 2002/07/30 12:41:25 wiz Exp $
#

DISTNAME=	choparp-20021107
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=choparp/}

MAINTAINER=	dbj@netbsd.org
HOMEPAGE=	http://choparp.sf.net/
COMMENT=	Simple proxy arp daemon

MANCOMPRESSED_IF_MANZ=	yes

.include "../../mk/bsd.pkg.mk"
