# $NetBSD: Makefile,v 1.1 2002/06/17 05:06:49 shell Exp $

DISTNAME=	KoreanCodecs-2.0.4
PKGNAME=	${PYPKGPREFIX}-koCodecs-2.0.4
CATEGORIES=	converters
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=koco/}

MAINTAINER=	perky@fallin.lv
HOMEPAGE=	http://sourceforge.net/projects/koco
COMMENT=	Python Unicode codecs for Korean charsets

PYDISTUTILSPKG=	yes
PYBINMODULE=	yes

.include "../../lang/python/extension.buildlink.mk"
.include "../../mk/bsd.pkg.mk"
