# $NetBSD$

DISTNAME=		dnstracer-1.7
CATEGORIES=		net
MASTER_SITES=		http://www.mavetju.org/download/

MAINTAINER=		tech-pkg@netbsd.org
HOMEPAGE=		http://www.mavetju.org/unix/general.php
COMMENT=		tool to trace dns queries

USE_BUILDLINK2=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
