# $NetBSD: Makefile.version,v 1.1.1.1 2008/09/07 00:56:15 bjs Exp $
#

MPG123_DISTVERSION=	1.5.1
###
###	This version number is found as LIBMPG123_VERSION in configure.ac.
###
LIBMPG123_VERSION=	0.7.0
