# $NetBSD: Makefile,v 1.24 2011/02/09 12:37:58 taca Exp $

DISTNAME=	activesupport-${RUBY_RAILS2_VERSION}
CATEGORIES=	devel

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://rubyforge.org/projects/activesupport/
COMMENT=	Collection of classes and extensions for Rails
LICENSE=	mit

RUBY_RAILS=	2

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
