# $NetBSD: buildlink3.mk,v 1.1 2004/02/19 01:06:43 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TREMOR_BUILDLINK3_MK:=	${TREMOR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	tremor
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ntremor}
BUILDLINK_PACKAGES+=	tremor

.if !empty(TREMOR_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.tremor+=	tremor>=1.0.2
BUILDLINK_PKGSRCDIR.tremor?=	../../audio/tremor
.endif	# TREMOR_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
