# $NetBSD$

DISTNAME=	chemarrow.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.9
TEXLIVE_REV=	17146

MAINTAINER=	nico@orgrim.net
COMMENT=	Documentation for tex-chemarrow

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
