# $NetBSD: buildlink3.mk,v 1.1 2009/10/15 12:39:42 hasso Exp $

BUILDLINK_TREE+=	xsd

.if !defined(XSD_BUILDLINK3_MK)
XSD_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.xsd+=	xsd>=3.2
BUILDLINK_ABI_DEPENDS.xsd+=	xsd>=3.2
BUILDLINK_PKGSRCDIR.xsd?=	../../devel/xsd

BUILDLINK_DEPMETHOD.xsd?=	build
.endif # XSD_BUILDLINK3_MK

BUILDLINK_TREE+=	-xsd
