# $NetBSD: Makefile,v 1.12 2007/10/11 21:26:10 adam Exp $

PKGNAME=	wmx-${WMX_VERS}
PKGREVISION=	3
COMMENT=	Another X11 window manager based on wm2

PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../wm/wmx/Makefile.common"
.include "../../mk/bsd.pkg.mk"
