# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBOWFAT_BUILDLINK3_MK:=	${LIBOWFAT_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libowfat
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibowfat}
BUILDLINK_PACKAGES+=	libowfat
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libowfat

.if ${LIBOWFAT_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libowfat+=	libowfat>=0.26
BUILDLINK_PKGSRCDIR.libowfat?=		../../devel/libowfat
BUILDLINK_DEPMETHOD.libowfat?=		build
.endif	# LIBOWFAT_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
