# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DATLIB_BUILDLINK3_MK:=	${DATLIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	DatLib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NDatLib}
BUILDLINK_PACKAGES+=	DatLib

.if !empty(DATLIB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.DatLib+=	DatLib>=2.2
BUILDLINK_PKGSRCDIR.DatLib?=	../../emulators/DatLib
.endif	# DATLIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
