# $NetBSD$

DISTNAME=	pst-node.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.15
TEXLIVE_REV=	21550

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-pst-node

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
