# $NetBSD: Makefile,v 1.6 2006/05/21 18:44:46 joerg Exp $
#

PKGNAME=		${PYPKGPREFIX}-gobject-2.12.1

.include "Makefile.common"

.include "../../lang/python/extension.mk"
.include "../../devel/py-gobject-shared/buildlink3.mk"
.include "../../devel/glib2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
