# $NetBSD: Makefile,v 1.5 2006/04/12 09:28:00 drochner Exp $
#

PKGNAME=		${PYPKGPREFIX}-gobject-2.10.1
PKGREVISION=		1

.include "Makefile.common"

.include "../../lang/python/extension.mk"
.include "../../devel/py-gobject-shared/buildlink3.mk"
.include "../../devel/glib2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
