# $NetBSD$
#

DISTNAME=		pychecker-0.8.17
CATEGORIES=		devel
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=pychecker/}

MAINTAINER=		rillig@NetBSD.org
HOMEPAGE=		http://pychecker.sourceforge.net/
COMMENT=		Static analyzer for Python programs

USE_TOOLS+=		pkg-config
PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
