# $NetBSD: Makefile,v 1.1.1.1 2002/09/29 00:13:14 wiz Exp $
#

DISTNAME=	bktr2jpeg-1.0
CATEGORIES=	graphics
MASTER_SITES=	http://core.de/~coto/projects/bktr2jpeg/

MAINTAINER=	coto@core.de
HOMEPAGE=	http://core.de/~coto/projects/bktr2jpeg/
COMMENT=	Write jpeg image captured from /dev/bktr to file

USE_BUILDLINK2=	YES

.include "../../graphics/jpeg/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
