# $NetBSD: buildlink3.mk,v 1.3 2004/10/03 00:13:06 tv Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SOX_BUILDLINK3_MK:=	${SOX_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	sox
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsox}
BUILDLINK_PACKAGES+=	sox

.if !empty(SOX_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.sox+=		sox>=12.17.4
BUILDLINK_RECOMMENDED.sox+=	sox>=12.17.4nb3
BUILDLINK_PKGSRCDIR.sox?=	../../audio/sox
.endif	# SOX_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
