# $NetBSD: Makefile,v 1.2 2001/02/17 09:07:13 agc Exp $
#

DISTNAME=	intercal-0.20
CATEGORIES=	lang
MASTER_SITES=	http://www.tuxedo.org/~esr/intercal/

MAINTAINER=	dillo@giga.or.at
HOMEPAGE=	http://www.tuxedo.org/~esr/intercal/
COMMENT=	the ultimate language for obfuscation and job security

.include "../../mk/bsd.pkg.mk"
