# $NetBSD$

DISTNAME=	l3packages.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.2900
TEXLIVE_REV=	24257

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-l3packages

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
