# $NetBSD: Makefile,v 1.11 2004/07/05 14:25:55 taya Exp $

MOZILLA=	firefox-gtk2

COMMENT=	Lightweight gecko-based web browser built with GTK2

MOZILLA_USE_GTK2=	# defined
MOZILLA_USE_XFT=	YES

.include "../../www/firefox/Makefile-firefox.common"
