# $NetBSD: Makefile,v 1.3 2003/07/21 17:24:24 martti Exp $
#

DISTNAME=		qlogtools-3.1
CATEGORIES=		sysutils
MASTER_SITES=		${HOMEPAGE}

MAINTAINER=		zuntum@NetBSD.org
HOMEPAGE=		http://untroubled.org/qlogtools/
COMMENT=		Tools useful in analyzing logs from qmail and other pkgs

BUILD_TARGET=		all

DJB_RESTRICTED=		NO
BGWARE_INSTALLER=	YES

.include "../../mk/djbware.mk"
.include "../../mk/bsd.pkg.mk"
