# $NetBSD: Makefile,v 1.7 2012/06/14 07:45:07 sbd Exp $

KOFFICE_LANGUAGE=	English (Great Britain)
KOFFICE_LANGCODE=       en_GB
PKGREVISION=		1

.include "../../misc/koffice/l10n.mk"
.include "../../mk/bsd.pkg.mk"
