# $NetBSD$

DISTNAME=	gpgme-0.3.0
CATEGORIES=	security
MASTER_SITES=	ftp://ftp.gnupg.org/gcrypt/alpha/gpgme/

MAINTAINER=	oishi@ims.ac.jp
HOMEPAGE=	http://www.gnupg.org/gpgme.html
COMMENT=	GnuPG Made Easy

DEPENDS+=	gnupg-1.0.6:../../security/gnupg

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
