# $NetBSD: Makefile,v 1.1.1.1 2009/07/12 03:32:57 minskim Exp $

DISTNAME=	geometry.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-5.3
TEXLIVE_REV=	17466

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-geometry

CONFLICTS+=	teTeX-texmf<=3.0nb18

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
