# $NetBSD: Makefile,v 1.5 2005/11/08 18:22:09 jlam Exp $

DISTNAME=	kcfonts-1.05
CATEGORIES=	fonts
MASTER_SITES=	ftp://freebsd.sinica.edu.tw/pub/distfiles/

MAINTAINER=	kevlo@midassol.com
COMMENT=	Kuo Chauo Chinese Fonts collection

WRKSRC=		${WRKDIR}
USE_X11BASE=	yes
FONTS_DIRS.x11=	lib/X11/fonts/local

.include "../../mk/bsd.pkg.mk"
