# $NetBSD: Makefile,v 1.10 2012/09/15 10:03:38 obache Exp $
#

GST_PLUGINS1_NAME=	spc
GST_PLUGINS1_DIRS=	ext/spc

.include "../../multimedia/gst-plugins1-bad/Makefile.common"

.include "../../audio/libopenspc/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
