# $NetBSD: Makefile,v 1.1.1.1 2009/04/15 05:12:25 minskim Exp $

DISTNAME=	ruhyphen
PKGNAME=	tex-${DISTNAME}-1.6
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Russian hyphenation

CONFLICTS+=	teTeX-texmf<=3.0nb12

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
