# $NetBSD: Makefile,v 1.9 2005/08/19 03:55:00 schmonz Exp $

DISTNAME=       	djbfft-0.76
CATEGORIES=     	math
MASTER_SITES=   	http://cr.yp.to/djbfft/

MAINTAINER=     	tech-pkg@NetBSD.org
HOMEPAGE=       	http://cr.yp.to/djbfft.html
COMMENT=        	Extremely fast library for floating-point convolution

DJB_RESTRICTED=		YES
NOT_FOR_PLATFORM=	IRIX-*-*

.include "../../mk/djbware.mk"
.include "../../mk/bsd.pkg.mk"
