# $NetBSD: Makefile,v 1.3 2003/03/16 14:02:23 cjep Exp $

DISTNAME=	diction-1.02
CATEGORIES=	textproc
MASTER_SITES=	http://www.moria.de/~michael/diction/

MAINTAINER=	xs@nitric.net
HOMEPAGE=	http://www.gnu.org/software/diction/diction.html
COMMENT=	GNU version of diction and style

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
