# $NetBSD: Makefile,v 1.1.1.1 2009/07/07 23:15:24 minskim Exp $

DISTNAME=	multirow
PKGNAME=	tex-${DISTNAME}-1.6
TEXLIVE_REV=	17256

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Create tabular cells spanning multiple rows

CONFLICTS+=	teTeX-texmf<=3.0nb16

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
