# $NetBSD: Makefile,v 1.12 2012/09/11 20:32:11 asau Exp $

DISTNAME=	clustalw-2.1
CATEGORIES=	biology
MASTER_SITES=	ftp://ftp.ebi.ac.uk/pub/software/clustalw2/2.1/ \
		http://www.clustal.org/download/current/

MAINTAINER=	babafou@babafou.eu.org
HOMEPAGE=	http://bips.u-strasbg.fr/fr/Documentation/ClustalW/
COMMENT=	General purpose multiple alignment program for DNA or proteins
LICENSE=	gnu-gpl-v3 AND gnu-lgpl-v3

PKG_INSTALLATION_TYPES=	overwrite pkgviews

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++

INSTALLATION_DIRS=	bin

.include "../../mk/bsd.pkg.mk"
