# $NetBSD$
#

DISTNAME=		plugger-5.1.3
CATEGORIES=		www
MASTER_SITES=		http://fredrik.hubbe.net/plugger/

MAINTAINER=		reinoud@NetBSD.org
HOMEPAGE=		http://fredrik.hubbe.net/plugger/
COMMENT=		Generic mozilla family plugin using external programs

WRKSRC=			${WRKDIR}/plugger-5.1.3
USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

USE_X11=		yes

.include "../../mk/bsd.pkg.mk"
