# $NetBSD$
#

    SUBDIR += gaim
    SUBDIR += icb
    SUBDIR += icqlib
    SUBDIR += ircII
    SUBDIR += ircu
    SUBDIR += kicq
    SUBDIR += kxicq
    SUBDIR += libirc
    SUBDIR += micq
    SUBDIR += sirc
    SUBDIR += tkicb
    SUBDIR += tkirc
    SUBDIR += xchat
    SUBDIR += zenicb
    SUBDIR += zircon

.include "../mk/bsd.pkg.subdir.mk"
