#!/bin/sh
#
# $NetBSD: DEINSTALL,v 1.1 2001/11/01 01:00:41 zuntum Exp $

PKGNAME=$1
STAGE=$2

case ${STAGE} in
POST-DEINSTALL)
	CONFDIR=${PKG_PREFIX}/etc/nmh

	cat << EOF
===========================================================================
If you won't be using ${PKGNAME} any longer, you may want to remove the
following directories:

	${CONFDIR}
===========================================================================
EOF
	;;
esac
exit 0
