# $NetBSD$
#

DISTNAME=	echoping-3.0.1
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.internatif.org/pub/unix/echoping/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://echoping.sourceforge.net/

GNU_CONFIGURE=	YES
CONFIGURE_ARGS+=--enable-icp

.include "../../mk/bsd.pkg.mk"
