# $NetBSD$
# TeX Live Revision 9907

DISTNAME=	xltxtra.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.4

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-xltxtra

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
