# $NetBSD: Makefile,v 1.27 2002/10/02 03:11:19 rh Exp $
#

COMMENT=	Network news

SUBDIR+=	cg
SUBDIR+=	inn
SUBDIR+=	knews
SUBDIR+=	leafnode
SUBDIR+=	newscache
SUBDIR+=	newsfetch
SUBDIR+=	nn
SUBDIR+=	nntpcache
SUBDIR+=	nntpclnt
SUBDIR+=	pan
SUBDIR+=	pan-gnome
SUBDIR+=	slrn
SUBDIR+=	suck
SUBDIR+=	tin
SUBDIR+=	trn
SUBDIR+=	xrn

.include "../mk/bsd.pkg.subdir.mk"
