# $NetBSD: Makefile,v 1.16 2000/02/25 01:04:15 wiz Exp $
#

    SUBDIR += inn
    SUBDIR += knews
    SUBDIR += newscache
    SUBDIR += nn
    SUBDIR += nntpcache
    SUBDIR += nntpclnt
    SUBDIR += slrn
    SUBDIR += suck
    SUBDIR += tin
    SUBDIR += trn
    SUBDIR += xrn

.include "../mk/bsd.pkg.subdir.mk"
