# $NetBSD$

DISTNAME=	esint.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.1
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-esint

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
