# $NetBSD: Makefile,v 1.1.1.1 2006/05/16 21:41:36 jlam Exp $

WBM_NAME=	htaccess-htpasswd

WBM_DEPEND_MODULES=	apache useradmin

COMMENT=	Webmin module to protect Apache web-accessible directories

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
