# $NetBSD: Makefile,v 1.1.1.1 2009/04/29 05:28:55 minskim Exp $

DISTNAME=	marvosym.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.1
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-marvosym

CONFLICTS+=	teTeX-texmf<=3.0nb13

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
