# $NetBSD: Makefile,v 1.3 2010/09/19 23:20:33 minskim Exp $

DISTNAME=	tools.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2010
TEXLIVE_REV=	20258

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-tools

CONFLICTS+=	teTeX-texmf<=3.0nb13

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
