# $NetBSD$

DISTNAME=	dgpsip-1.28
CATEGORIES=	misc
MASTER_SITES=	http://www.wsrcc.com/wolfgang/ftp/

MAINTAINER=     wsr+dgpsip@wsrcc.com
HOMEPAGE=	http://www.wsrcc.com/wolfgang/gps/dgps-ip.html

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
