# $NetBSD: Makefile,v 1.1.1.1 2011/02/20 08:01:08 ryoon Exp $
#

HELPLANGUAGE=		pl

DISTNAME=		gimp-help-2.6.1-html-${HELPLANGUAGE}
PKGNAME=		gimp-docs-${HELPLANGUAGE}-${DISTNAME:S/gimp-help-//:S/-html-${HELPLANGUAGE}//}

.include "../../graphics/gimp-docs-en/Makefile.common"

COMMENT=		Documentation package for The Gimp image manipulation software
