# $NetBSD$
# TeX Live Revision 11886

DISTNAME=	txfonts
PKGNAME=	tex-${DISTNAME}-2008.11886

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Times-like fonts in support of mathematics

CONFLICTS+=	teTeX-texmf<=3.0nb19

TEX_MAP_FILES+=	txfonts.map

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
