# $NetBSD: Makefile,v 1.2 2006/05/19 17:14:53 jlam Exp $

WBM_NAME=	quota

WBM_DEPEND_MODULES+=	mount

COMMENT=	Webmin module to setup disk quotas

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
