# $NetBSD: Makefile,v 1.1.1.1 2010/04/29 22:45:11 minskim Exp $

DISTNAME=	selectp
PKGNAME=	tex-${DISTNAME}-1.0
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Select pages to be output

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
