# $NetBSD$

DISTNAME=	hyphenat.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.3c
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-hyphenat

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
