# $NetBSD: Makefile,v 1.1.1.1 2009/11/01 23:44:45 seb Exp $

DISTNAME=	compass-susy-plugin-0.8.0
CATEGORIES=	www

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.oddbird.net/susy/
COMMENT=	Compass plugin grid system
LICENSE=	modified-bsd

DEPENDS+=	${RUBY_PKGPREFIX}-compass-[0-9]*:../../www/ruby-compass

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
