# $NetBSD$
#

DISTNAME=		spellcast
PKGNAME=		spellcast-1.2
CATEGORIES=		games x11
MASTER_SITES=		http://www.edoc.com/zarf/ftp/
EXTRACT_SUFX=		.tar.Z

MAINTAINER=		root@garbled.net

USE_X11=		yes

.include "../../mk/bsd.pkg.mk"
