# $NetBSD$

DISTNAME=	pst-fill.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.01
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-pst-fill

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
