# $NetBSD$

DISTNAME=	verbasef.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.1
TEXLIVE_REV=	21922

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-verbasef

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
