# $NetBSD: Makefile,v 1.3 1998/07/22 09:58:50 frueauf Exp $

DISTNAME=	f2c-19980516p1
CATEGORIES=	lang
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	mcmahill@alum.mit.edu
HOMEPAGE=	http://www.netlib.org/f2c/index.html

CONFLICTS=	egcs-current-19980608

WRKSRC=		${WRKDIR}/f2c

.include "../../mk/bsd.pkg.mk"
