# $NetBSD$

R_PKGNAME=	foreign
R_PKGVER=	0.5-5

MAINTAINER=	markd@netbsd.org
COMMENT=	Read data stored by Minitab, S, SAS, SPSS, Stata, ...

PLIST_SRC=	/dev/null

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
