# $NetBSD: Makefile,v 1.1.1.1 2001/03/16 14:15:53 wiz Exp $
#

DISTNAME=	xwit-3.4
PKGREVISION=	1
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB:=utilities/}

MAINTAINER=	seb@netbsd.org
COMMENT=	Utility for calling X11 functions from the shell

USE_IMAKE=	yes

.include "../../mk/bsd.pkg.mk"
