# $NetBSD: Makefile,v 1.7 1999/04/15 20:39:50 tron Exp $
# FreeBSD Id: Makefile,v 1.7 1996/11/18 09:56:45 asami Exp 
#

DISTNAME=	xsnow-1.41
CATEGORIES=	x11
MASTER_SITES=	http://www.euronet.nl/~rja/Xsnow/
HOMEPAGE=	http://www.euronet.nl/~rja/Xsnow/

MAINTAINER=	is@netbsd.org

USE_IMAKE=	yes

.include "../../mk/bsd.pkg.mk"
