# $NetBSD: Makefile,v 1.18 2010/10/15 11:38:11 taca Exp $

DISTNAME=	actionmailer-2.3.11
CATEGORIES=	mail

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://rubyforge.org/projects/actionmailer/
COMMENT=	Ruby framework for designing email-service layers
LICENSE=	mit

DEPENDS+=	${RUBY_PKGPREFIX}-actionpack>=2.3.11<2.3.12:../../www/ruby-actionpack

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
