# $NetBSD: Makefile,v 1.5 2005/07/05 19:53:40 christos Exp $
#

DISTNAME=	vis-0.1
CATEGORIES=	textproc
MASTER_SITES=	ftp://ftp.astron.com/pub/people/christos/

MAINTAINER=	christos@NetBSD.org
COMMENT=	Convert strings from/to a visual format

MAKE_ENV+=	BINOWN=${BINOWN:Q} BINGRP=${BINGRP:Q}	\
		MANOWN=${MANOWN:Q} MANGRP=${MANGRP:Q}

.include "../../mk/bsd.pkg.mk"
