#!/bin/sh
#
#	$NetBSD: openapp,v 1.1 2002/09/27 23:56:30 rh Exp $
#
# GNUstep openapp wrapper
. @PREFIX@/share/GNUstep/System/Library/Makefiles/GNUstep.sh
@PREFIX@/share/GNUstep/System/Tools/openapp "$@"
