# $NetBSD$

DISTNAME=	statex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.6
TEXLIVE_REV=	20306

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-statex

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
