# $NetBSD$

DISTNAME=	euler.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.5
TEXLIVE_REV=	17261

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-euler

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
