# $NetBSD: Makefile,v 1.1.1.1 2008/04/29 18:02:05 jlam Exp $

DISTNAME=	will_paginate-2.3.14
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME:S/_/-/}
CATEGORIES=	textproc
LICENSE=	mit

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/mislav/will_paginate/wikis
COMMENT=	Pagination for views of model queries

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
