# $NetBSD$
# TeX Live Revision 15878

DISTNAME=	rcsinfo
PKGNAME=	tex-${DISTNAME}-1.11

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Support for the revision control system

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
