#!/bin/sh
#
# $NetBSD$

case ${STAGE} in
DEINSTALL)
	if [ -d /var/spool/fax ]; then
		filecount="`${FIND} /var/spool/fax -type f 2>/dev/null | wc -l`"
		if [ $filecount -eq 0 ]; then
			${ECHO} "Removing empty fax spool directories..."
			${RM} -r /var/spool/fax
		fi
	fi
	;;
esac
