# $NetBSD$
# TeX Live Revision 16936

DISTNAME=	ifluatex
PKGNAME=	tex-${DISTNAME}-1.2
DIST_SUBDIR=	${PKGNAME_NOREV}.16936

MAINTAINER=	minskim@NetBSD.org
COMMENT=	The \ifluatex switch for TeX

CONFLICTS+=	tex-oberdiek<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
