# $NetBSD: Makefile,v 1.4 2001/03/16 13:28:38 wiz Exp $

PKGNAME=		freetype-lib-${FT_VERS}

COMMENT=		TrueType font rendering engine and library API

CONFIGURE_ARGS+=	--without-x

ALL_TARGET=		ttlib ttpo
INSTALL_TARGET=		install-ttlib install-ttpo

.include "../../graphics/freetype-lib/Makefile.common"
