# $NetBSD: Makefile.common,v 1.12 2007/05/31 12:48:35 dmcmahill Exp $
#

DIST_SUBDIR=	geda
PKGVERSION=	1.4.0
MASTER_SITES=	ftp://ftp.geda.seul.org/pub/geda/release/v1.4/${PKGVERSION}/ \
		http://www.geda.seul.org/release/v1.4/${PKGVERSION}/

USE_TOOLS+=		gmake
CONFIGURE_ARGS+=	--disable-update-desktop-database
CONFIGURE_ARGS+=	--disable-update-mime-database
USE_PKGLOCALEDIR=	yes
