# $NetBSD$
# TeX Live Revision 15878

DISTNAME=	placeins-plain
PKGNAME=	tex-${DISTNAME}-2.0

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Insertions that keep their place

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
