# $NetBSD: Makefile,v 1.1.1.1 2008/07/19 18:23:46 ahoka Exp $

VERSION=	0.12
DISTNAME=	fy_NL
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Frisian dictionary for hunspell

.include "../../textproc/hunspell/Makefile.common"

.include "../../mk/bsd.pkg.mk"
