# $NetBSD$

BUILDLINK_TREE+=	mythes

.if !defined(MYTHES_BUILDLINK3_MK)
MYTHES_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.mythes+=	mythes>=1.2.2
BUILDLINK_PKGSRCDIR.mythes?=	../../wip/libmythes
.endif	# MYTHES_BUILDLINK3_MK

BUILDLINK_TREE+=	-mythes
