# $NetBSD$
#
MASTER_SITES=	ftp://ftp.kde.org/pub/kde/stable/2.1/distribution/tar/generic/src/ \
		ftp://ftp.us.kde.org/pub/kde/stable/2.1/distribution/tar/generic/src/ \
		ftp://ftp.de.kde.org/pub/kde/stable/2.1/distribution/tar/generic/src/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	skrll@netbsd.org
HOMEPAGE=	http://www.kde.org/
