# $NetBSD$

DISTNAME=	arabtex
PKGNAME=	tex-${DISTNAME}-3.11s
TEXLIVE_REV=	17095

MAINTAINER=	kamelderouiche@yahoo.com
COMMENT=	Macros and fonts for typesetting Arabic

TEX_MIXEDMAP_FILES+=	arabtex.map

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
