# $NetBSD$

DISTNAME=	daemon_controller-1.0.0
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	net

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/FooBarWidget/daemon_controller
COMMENT=	Library for robust daemon management
LICENSE=        mit

GEM_BUILD=	gemspec

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
