# $NetBSD: Makefile,v 1.3 2007/02/19 21:52:41 joerg Exp $

WBM_NAME=	cluster-cron

COMMENT=	Webmin module to schedule cron jobs within a Webmin cluster

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
