# $NetBSD: Makefile,v 1.1.1.1 2008/04/04 15:21:06 jlam Exp $

DISTNAME=	builder-2.1.2
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://onestepback.org/
COMMENT=	Programatic generation of XML markup in Ruby
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
