# $NetBSD: Makefile,v 1.4 1999/01/30 23:18:50 agc Exp $

DISTNAME=		fnlib-0.4
PKGNAME=		fnlib-0.4
CATEGORIES=		x11 graphics
MASTER_SITES=		ftp://ftp.enlightenment.org/pub/enlightenment/enlightenment/

MAINTAINER=		root@garbled.net

DEPENDS+=		imlib-1.9.4:../../graphics/imlib

GNU_CONFIGURE=		yes
USE_GMAKE=		yes
USE_X11BASE=		yes

.include "../../mk/bsd.pkg.mk"
