# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TOMOE_BUILDLINK3_MK:=	${TOMOE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	tomoe
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ntomoe}
BUILDLINK_PACKAGES+=	tomoe
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}tomoe

.if ${TOMOE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.tomoe+=	tomoe>=0.6.0
BUILDLINK_PKGSRCDIR.tomoe?=	../../inputmethod/tomoe
.endif	# TOMOE_BUILDLINK3_MK

.include "../../devel/glib2/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
