# $NetBSD$

DISTNAME=	section
PKGNAME=	tex-${DISTNAME}-2011
TEXLIVE_REV=	20180

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Modifying section commands in LaTeX

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
