# $NetBSD: Makefile,v 1.1 1998/07/02 20:43:19 perry Exp $
#

DISTNAME=       STk-3.99.2
CATEGORIES=	lang
MASTER_SITES=	ftp://kaolin.unice.fr/pub/STk/

MAINTAINER=	perry@NetBSD.ORG

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
