# $NetBSD$

DISTNAME=	multi_json-1.0.4
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-userse@NetBSD.org
HOMEPAGE=	http://github.com/intridea/multi_json
COMMENT=	general-purpose swappable JSON backend library
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
