# $NetBSD$
#

DISTNAME=	gperf-2.7
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GNU}

MAINTAINER=	tv@netbsd.org

GNU_CONFIGURE=	yes
MAN1=		gperf.1
INFO_FILES=	gperf.info
USE_GTEXINFO=	yes

.include "../../mk/bsd.pkg.mk"
