# $NetBSD$

R_PKGNAME=	survival
R_PKGVER=	2.9-4

MAINTAINER=	markd@netbsd.org
COMMENT=	Survival analysis, including penalised likelihood.

PLIST_SRC=	/dev/null

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
