# $NetBSD: Makefile,v 1.22 2003/04/16 15:51:22 salo Exp $
#

.include "Makefile.common"

COMMENT=	The Open Source Network Intrusion Detection System

USE_BUILDLINK2=	YES

.include "../../net/libpcap/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
