#!/bin/sh
#
# $NetBSD: DEINSTALL,v 1.1.1.1 2002/08/06 14:04:34 wiz Exp $

PKGNAME=$1
STAGE=$2

XPDFRC=@PKG_SYSCONFDIR@/xpdfrc

case ${STAGE} in
DEINSTALL)
	;;

POST-DEINSTALL)
	@SED@ -e "/raditional/d" ${XPDFRC} > ${XPDFRC}.tmp
	@SED@ -e "/big5/d" -e "/Ar[ph][ph]ic fonts, you may/d" ${XPDFRC}.tmp > ${XPDFRC}
	@RM@ -f ${XPDFRC}.tmp
	;;

*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
exit 0
