# $NetBSD: Makefile.common,v 1.5 2012/10/31 11:17:26 asau Exp $
# used by devel/lua-stdlib-doc/Makefile
# used by devel/lua-stdlib/Makefile

DISTNAME=		stdlib-28
PKGNAME=		lua-${DISTNAME}
CATEGORIES=		devel
MASTER_SITES=		http://cloud.github.com/downloads/rrthomas/lua-stdlib/
EXTRACT_SUFX=		.zip

HOMEPAGE=		https://github.com/rrthomas/lua-stdlib
LICENSE=		mit

DISTINFO_FILE=		${.CURDIR}/../../devel/lua-stdlib/distinfo

NO_BUILD=		yes
NO_CONFIGURE=		yes
