# $NetBSD$
#

DISTNAME=	koth-0.6
CATEGORIES=	games
MASTER_SITES=	http://www-unix.oit.umass.edu/~tetron/koth/

MAINTAINER=	hubertf@netbsd.org
HOMEPAGE=	http://www-unix.oit.umass.edu/~tetron/koth/

GNU_CONFIGURE=	YES
CONFIGURE_ENV+=	CC="cc -I${LOCALBASE}/include"

.include "../../mk/bsd.pkg.mk"
