# $NetBSD$

DISTNAME=	pdfpages
PKGNAME=	tex-${DISTNAME}-0.4l
TEXLIVE_REV=	20796

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Include PDF documents in LaTeX

CONFLICTS=	teTeX-texmf<=3.0nb29

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
