# $NetBSD: Makefile,v 1.21 2011/02/09 12:39:41 taca Exp $

DISTNAME=	activerecord-${RUBY_RAILS2_VERSION}
CATEGORIES=	databases

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://rubyforge.org/projects/activerecord/
COMMENT=	Object-relation mapping put on rails
LICENSE=	mit

RUBY_RAILS=	2

DEPENDS+=	${RUBY_ACTIVESUPPORT_DEPENDS}

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
