# $NetBSD: Makefile,v 1.2 2010/09/14 00:18:15 minskim Exp $

DISTNAME=	cyrillic
PKGNAME=	tex-${DISTNAME}-2010
TEXLIVE_REV=	20254

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Support for Cyrillic fonts in LaTeX

CONFLICTS+=	teTeX-texmf<=3.0nb24

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
