#!/bin/sh
#
# $NetBSD$
#

case $2 in
    PRE-INSTALL)
        ;;
    POST-INSTALL)
    	for i in backup store store/trash download work ; do
	    mkdir -p @@PREFIX@@/$i
	done
	;;
    *)
	echo "Unexpected Argument $2!!"
	exit 1
	;;
esac

exit 0
