# $NetBSD$

DISTNAME=	romanneg.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2011
TEXLIVE_REV=	20087

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-romanneg
LICENSE=	public-domain

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
