# $NetBSD: Makefile,v 1.2 2006/12/02 19:04:26 gdt Exp $
#

DISTNAME=		etcmanage-0.3
PKGREVISION=		1
CATEGORIES=		sysutils
MASTER_SITES=		http://acert.ir.bbn.com/downloads/etcmanage/

MAINTAINER=		gdt@NetBSD.org
HOMEPAGE=		http://acert.ir.bbn.com/downloads/etcmanage/
COMMENT=		Automatically manage files in /etc

USE_TOOLS+=		perl:run
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
