# $NetBSD: Makefile,v 1.7 2006/06/12 16:28:12 wiz Exp $
#

GST_PLUGINS0.10_NAME=	mpeg2dec
GST_PLUGINS0.10_DIRS=	ext/mpeg2dec

.include "../../multimedia/gst-plugins0.10-ugly/Makefile.common"

.include "../../multimedia/libmpeg2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
