# $NetBSD: Makefile,v 1.4 2010/07/11 17:41:03 joerg Exp $

WBM_NAME=	fetchmail

COMMENT=	Webmin module for configuring fetchmail

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
