# $NetBSD: Makefile,v 1.2 2007/02/19 21:52:42 joerg Exp $

WBM_NAME=	fetchmail

COMMENT=	Webmin module for configuring fetchmail

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
