# $NetBSD: Makefile,v 1.10 2012/09/15 10:03:37 obache Exp $
#

GST_PLUGINS1_NAME=	faad
GST_PLUGINS1_DIRS=	ext/faad

.include "../../multimedia/gst-plugins1-bad/Makefile.common"

.include "../../audio/faad2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
