# $NetBSD$

CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	${R_HOMEPAGE_BASE}/genetics/
COMMENT=	Classification and regression based on a forest of trees

R_PKGNAME=	randomForest
R_PKGVER=	4.5-34

.include "../../adam/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
