# $NetBSD: Makefile,v 1.8 2000/09/12 16:52:57 jlam Exp $
#

DISTNAME=		texi2html-1.64
CATEGORIES=		textproc
MASTER_SITES=		http://www.mathematik.uni-kl.de/~obachman/Texi2html/Distrib/

MAINTAINER=		tv@netbsd.org
HOMEPAGE=		http://www.mathematik.uni-kl.de/~obachman/Texi2html/

CONFLICTS=		teTeX-bin-1.0 teTeX-bin-1.0.[1234567]

USE_PERL5=		# defined
GNU_CONFIGURE=		# defined

.include "../../mk/bsd.pkg.mk"
