# $NetBSD: Makefile,v 1.4 2000/06/01 11:23:42 rh Exp $

DISTNAME=		libghttp-1.0.6
CATEGORIES=		www gnome
MASTER_SITES=		${MASTER_SITE_GNOME:=stable/sources/libghttp/}

MAINTAINER=		tron@netbsd.org
HOMEPAGE=		http://www.gnome.org/

GNU_CONFIGURE=		# defined
USE_LIBTOOL=		# defined
LTCONFIG_OVERRIDE=	${WRKSRC}/ltconfig

.include "../../mk/bsd.pkg.mk"
