# $NetBSD$

DISTNAME=		Test-Builder-Tester-1.01
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=Test/}

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://search.cpan.org/dist/Test-Builder-Tester/
COMMENT=		Perl5 module to test testsuites built with Test::Builder

PERL5_PACKLIST=		auto/Test/Builder/Tester/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
