# $NetBSD$

DISTNAME=	pst-circ.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.01
TEXLIVE_REV=	21599

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-pst-circ

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
