# $NetBSD: Makefile,v 1.3 2003/07/22 12:34:24 wiz Exp $

DISTNAME=	gocr-0.37
CATEGORIES=	textproc
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=jocr/}

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://sourceforge.net/projects/jocr
COMMENT=	GOCR is a set of OCR tools

GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_BUILDLINK2= yes

.include "../../mk/bsd.pkg.mk"
