# $NetBSD$

DISTNAME=	pst-vue3d.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.24
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-pst-vue3d

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
