# $NetBSD$
#

DISTNAME=	bozohttpd-5.00
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_LOCAL}
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.eterna.com.au/bozohttpd/

.include "../../mk/bsd.pkg.mk"
