# $NetBSD: Makefile,v 1.1.1.1 2009/04/15 05:05:13 minskim Exp $
# TeX Live Revision 15878

DISTNAME=	hyph-utf8
PKGNAME=	tex-${DISTNAME}-2009

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Hyphenation patterns expressed in UTF-8

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
