# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBPQXX_BUILDLINK3_MK:=	${LIBPQXX_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libpqxx
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibpqxx}
BUILDLINK_PACKAGES+=	libpqxx

.if !empty(LIBPQXX_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libpqxx+=	libpqxx>=2.5.0
BUILDLINK_PKGSRCDIR.libpqxx?=	../../databases/libpqxx
.endif	# LIBPQXX_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
