# $NetBSD$

DISTNAME=	tilt-1.3.2
CATEGORIES=	textproc

MAINTAINER=	obache@NetBSD.org
HOMEPAGE=	http://github.com/rtomayko/tilt/
COMMENT=	Generic interface to multiple Ruby template engines
LICENSE=	mit

PKG_DESTDIR_SUPPORT=	user-destdir

RUBYGEM_OPTIONS+=	--format-executable

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
