# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HRE_BUILDLINK3_MK:=	${HRE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	hre
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhre}
BUILDLINK_PACKAGES+=	hre

.if !empty(HRE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.hre+=		hre>=0.9.7
BUILDLINK_PKGSRCDIR.hre?=	../../textproc/hre
.endif	# HRE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
