# $NetBSD$
#

DISTNAME=	fire-1.0
CATEGORIES=	games
MASTER_SITES=	http://www.libsdl.org/projects/fire/src/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.libsdl.org/projects/fire/index.html
COMMENT=	organic fireworks demo

DEPENDS+=	SDL>=1.1.6:../../devel/SDL

GNU_CONFIGURE=	YES
USE_X11=	YES

.include "../../mk/bsd.pkg.mk"
