# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBSIEVE_BUILDLINK3_MK:=	${LIBSIEVE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libsieve
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibsieve}
BUILDLINK_PACKAGES+=	libsieve
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libsieve

.if ${LIBSIEVE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libsieve+=	libsieve>=2.2.5
BUILDLINK_PKGSRCDIR.libsieve?=	../../mail/libsieve
.endif	# LIBSIEVE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
