# $NetBSD$
#

DISTNAME=	ratpoison-0.1.1
CATEGORIES=	wm
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=ratpoison/}

MAINTAINER=	zuntum@netbsd.org
HOMEPAGE=	http://ratpoison.sourceforge.net/
COMMENT=	Simple window manager with no fat library dependencies

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
