# $NetBSD$
# TeX Live Revision 17357

DISTNAME=	hyper
PKGNAME=	tex-${DISTNAME}-4.2d

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Hypertext cross referencing

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
