# $NetBSD$
# TeX Live Revision 17087

DISTNAME=	boxedminipage
PKGNAME=	tex-${DISTNAME}-2009

MAINTAINER=	minskim@NetBSD.org
COMMENT=	LaTeX package for producing framed minipages

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
