# $NetBSD: Makefile,v 1.2 2002/10/24 22:30:45 drochner Exp $

DISTNAME=	Calendar-1.0.10
PKGNAME=	zope25-Calendar-1.0.10
CATEGORIES=	www
MASTER_SITES=	http://www.zope.org/Members/jdavid/Calendar/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.zope.org/Members/jdavid/Calendar
COMMENT=	the Calendar Tag

ZOPE_COPYPRODUCT= zope-std-copyproduct-short
USE_BUILDLINK2=	yes

.include "../../www/zope25/product.mk"
.include "../../mk/bsd.pkg.mk"
