# $NetBSD: buildlink3.mk,v 1.8 2006/07/08 23:10:59 jlam Exp $

BUILDLINK_TREE+=	cln

.if !defined(CLN_BUILDLINK3_MK)
CLN_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.cln+=		cln>=1.1.6
BUILDLINK_ABI_DEPENDS.cln+=	cln>=1.1.9nb1
BUILDLINK_PKGSRCDIR.cln?=	../../math/cln
.endif # CLN_BUILDLINK3_MK

BUILDLINK_TREE+=	-cln
