#!/bin/sh
#
# $NetBSD$

PKGNAME=$1
STAGE=$2

XPDFRC=${PKG_PREFIX}/etc/xpdfrc

case ${STAGE} in
DEINSTALL)
	;;

POST-DEINSTALL)
	sed -e "/reek/d" ${XPDFRC} > ${XPDFRC}.tmp
	mv -f ${XPDFRC}.tmp ${XPDFRC}
	;;

*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
exit 0
