# $NetBSD: Makefile,v 1.24 2006/03/04 21:28:59 jlam Exp $
#

DISTNAME=	dflowers-1.2
PKGNAME=	xmms-${DISTNAME}
PKGREVISION=	4
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	pkgsrc-users@NetBSD.org
# HOMEPAGE=	http://www.shell.linux.se/bm/index.php?page=xmmsplugin
# AWOL
COMMENT=	XMMS plugin for dual flower scope

USE_LIBTOOL=		YES

.include "../../audio/xmms/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
