# $NetBSD: Makefile,v 1.7 2001/05/24 20:17:13 dmcmahill Exp $
#

DISTNAME=	dinotrace-9.1d
CATEGORIES=	cad
MASTER_SITES=	http://www.veripool.com/ftp/

MAINTAINER=	dmcmahill@netbsd.org
HOMEPAGE= 	http://www.veripool.com/dinotrace/
COMMENT=	tool for viewing the output of digital simulators

INFO_FILES=	dinotrace.info

USE_BUILDLINK_ONLY=	YES
GNU_CONFIGURE=		YES

.include "../../x11/lesstif/buildlink.mk"
.include "../../mk/bsd.pkg.mk"
