# $NetBSD$
#

DISTNAME=		xrestop-0.3
CATEGORIES=		x11
MASTER_SITES=		http://www.freedesktop.org/software/xrestop/

MAINTAINER=		reed@reedmedia.net
HOMEPAGE=		http://www.freedesktop.org/Software/xrestop
COMMENT=		X11 clients' server-side resource usage monitor

USE_X11=		yes
GNU_CONFIGURE=		yes

.include "../../devel/ncurses/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
