# $NetBSD: Makefile,v 1.5 2004/01/03 18:49:53 reed Exp $

.include "../../meta-pkgs/xfce4/Makefile.common"

PKGNAME=	xfce4-fm-icons-${XFCE4_VERSION}
DISTNAME=	xffm-icons-${XFCE4_VERSION}
CATEGORIES=	sysutils
COMMENT=	XFce4 filemanager icons

.include "../../sysutils/xfce4-fm/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
