# $NetBSD$

# used by www/py-werkzeug/Makefile
# used by www/py-werkzeug-docs/Makefile

DISTNAME=	Werkzeug-0.8.3
CATEGORIES=	www python
MASTER_SITES=	http://pypi.python.org/packages/source/W/Werkzeug/

DISTINFO_FILE=	${.CURDIR}/../../www/py-werkzeug/distinfo

MAINTAINER=	kleink@NetBSD.org
HOMEPAGE=	http://werkzeug.pocoo.org/
LICENSE=	modified-bsd

DOCDIR=		share/doc/${PYPKGPREFIX}-${DISTNAME:tl:C/-[^-]*$//}

PLIST_SUBST+=	DOCDIR=${DOCDIR}
