# $NetBSD$

DISTNAME=	ipaex
PKGNAME=	tex-${DISTNAME}-2011
TEXLIVE_REV=	25360

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	IPA and IPAex fonts for Kana and Kanji
LICENSE=	ipafont

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
