# $NetBSD: Makefile,v 1.1.1.1 2004/11/10 08:19:46 martin Exp $
#

PKG_DESTDIR_SUPPORT=	user-destdir

COMMENT=		WS 23xx weather station support software

INSTALLATION_DIRS+=	bin

.include "Makefile.common"
