# $NetBSD: Makefile,v 1.3 2003/07/17 21:34:26 grant Exp $
#

DISTNAME=	ex-040103
PKGNAME=	ex-20040103
CATEGORIES=	editors
MASTER_SITES=	http://ex-vi.berlios.de/archive/

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://ex-vi.berlios.de/
COMMENT=	Berkeley vi 3.7

.include "../../mk/bsd.pkg.mk"
