# $NetBSD$
# FreeBSD Id: Makefile,v 1.8 1997/10/29 17:09:53 max Exp
#

DISTNAME=	weblint-1.020
CATEGORIES=	www
MASTER_SITES=	ftp://ftp.cre.canon.co.uk/pub/weblint/

MAINTAINER=	frueauf@netbsd.org

MAN1=		weblint.1

.include "../../mk/bsd.pkg.mk"
