# $NetBSD$

DISTNAME=		mdocml-1.3.13
CATEGORIES=		devel
MASTER_SITES=		http://mdocml.bsd.lv/snapshots/

MAINTAINER=		kristaps@kth.se
HOMEPAGE=		http://mdocml.bsd.lv/
COMMENT=		mdoc macro compiler

.include "../../mk/bsd.pkg.mk"
