# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ZEPHYR_BUILDLINK3_MK:=	${ZEPHYR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	zephyr
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nzephyr}
BUILDLINK_PACKAGES+=	zephyr

.if !empty(ZEPHYR_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.zephyr+=	zephyr>=20010518nb1
BUILDLINK_PKGSRCDIR.zephyr?=	../../chat/zephyr
.endif	# ZEPHYR_BUILDLINK3_MK

.include "../../devel/readline/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
