#!/bin/sh
#
# $NetBSD$

PKGNAME=$1
STAGE=$2

case ${STAGE} in
PRE-INSTALL)
	;;
POST-INSTALL)
	cat <<EOF

=============================================================
If you customize namazu configuration, copy
@DOCDIR@/namazu.conf-dist to
@CONFDIR@ and edit them.
=============================================================

EOF
	;;
*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
exit 0
