# $NetBSD$

DISTNAME=	hyphen-hungarian.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2009
TEXLIVE_REV=	13822

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-hyphen-hungarian

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
