# New ports collection Makefile for: ctwm
# Version required:	3.4pl2
# Date created:         30th November 1997
# Whom:                 tron
#
# $NetBSD: Makefile,v 1.2 1997/12/20 11:08:11 kleink Exp $
#

DISTNAME=		ctwm-3.4pl2
CATEGORIES=		x11
MASTER_SITES=		${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	window_managers

MAINTAINER=		packages@netbsd.org

LIB_DEPENDS=		Xpm\\.4\\.:${PORTSDIR}/graphics/xpm

USE_IMAKE=		yes

.include <bsd.port.mk>
