# $NetBSD$
# TeX Live Revision 16813

DISTNAME=	capt-of.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2009

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-capt-of

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
