# $NetBSD: Makefile,v 1.1.1.1 2009/07/16 23:20:36 minskim Exp $

DISTNAME=	float.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.3d
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-float

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
