# $NetBSD: Makefile,v 1.1.1.1 2002/08/11 15:56:52 jschauma Exp $
#

PKGNAME=	cyberbase-ttf-2.0
PKGREVISION=	1
FONT_FILE=	Cyberbase.ZIP

COMMENT=	Cyberbit minus CJK subset, for ISO-8859-x languages

CONFLICTS=	cyberbit-ttf-*

.include "../../fonts/cyberbit-ttf/Makefile.common"
.include "../../mk/bsd.pkg.mk"
