# $NetBSD$

DISTNAME=	pst-uml.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.83
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-pst-uml

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
