# $NetBSD: Makefile,v 1.3 2010/02/10 15:31:25 joerg Exp $

DISTNAME=	pyPdf-1.13
PKGNAME=	${PYPKGPREFIX}-Pdf-1.13
CATEGORIES=	print python
MASTER_SITES=	http://pybrary.net/pyPdf/

MAINTAINER=	joerg@NetBSD.org
HOMEPAGE=	http://pybrary.net/pyPdf/
COMMENT=	PDF library
LICENSE=	modified-bsd

PKG_DESTDIR_SUPPORT=	user-destdir

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
