#!/bin/sh
#
# $NetBSD$
#

PKGNAME=$1

case $2 in
DEINSTALL)
	;;
POST-DEINSTALL)
	/bin/cat << EOF
===========================================================================
If you won't be using ${PKGNAME} any longer, you may want to remove the
hostname alias to "isectd" and remove the isect services listed in
/etc/services.
===========================================================================
EOF
	;;
*)
	echo "Unexpected argument: $2"
	exit 1
	;;
esac
exit 0
