# $NetBSD$

DISTNAME=	underscore.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2010
TEXLIVE_REV=	18261

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-underscore

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
