# $NetBSD: Makefile,v 1.1.1.1 2006/04/08 11:42:37 jmmv Exp $
#

USE_LANGUAGES+=		c++

.include "Makefile.common"

COMMENT+=		bad plugins

# bzip2 is likely present anyway, make it default
.include "../../archivers/bzip2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
