# $NetBSD: Makefile,v 1.3 2003/06/29 03:05:28 uebayasi Exp $
#
.include "../../shells/zsh/Makefile.common"

ZSH_VERSION=	4.1.1
ZSH_MAINTAINER=	uebayasi@netbsd.org

.include "../../mk/texinfo.mk"
.include "../../mk/bsd.pkg.mk"
