# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BOOST_BUILDLINK3_MK:=	${BOOST_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	boost
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nboost}
BUILDLINK_PACKAGES+=	boost

.if !empty(BOOST_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.boost+=	boost>=1.30.2
BUILDLINK_PKGSRCDIR.boost?=	../../devel/boost
.endif	# BOOST_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
