# $NetBSD$

.include "../../mk/bsd.prefs.mk"

BUILD_DEPENDS+=	gcc>=2.95.3:../../lang/gcc

.if (${OPSYS} == SunOS)
CC=	${LOCALBASE}/bin/gcc
CPP=	${LOCALBASE}/bin/cpp
CXX=	${LOCALBASE}/bin/g++
.else
CC=	${LOCALBASE}/gcc-2.95.3/bin/cc
CPP=	${LOCALBASE}/gcc-2.95.3/bin/cpp
CXX=	${LOCALBASE}/gcc-2.95.3/bin/c++
.endif
