# $NetBSD$

DISTNAME=	ragel-5.21
CATEGORIES=	devel
MASTER_SITES=	http://www.cs.queensu.ca/~thurston/ragel/

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://www.cs.queensu.ca/~thurston/ragel/
COMMENT=	State machine compiler

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++
USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
