# $NetBSD: Makefile,v 1.15 2008/01/12 11:36:31 adam Exp $

DISTNAME=	Codeville-0.1.16
PKGNAME=	codeville-0.1.16
PKGREVISION=	2
CATEGORIES=	devel scm
MASTER_SITES=	http://codeville.org/download/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://codeville.org/
COMMENT=	Distributed revision control system

PYDISTUTILSPKG=		yes

.include "../../lang/python/application.mk"
.include "../../lang/python/extension.mk"
.include "../../databases/py-bsddb3/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
