# $NetBSD: Makefile,v 1.8 2004/03/10 07:41:17 martti Exp $

.include "../../meta-pkgs/xfce4/Makefile.common"

DISTNAME=	xfce4-trigger-launcher-${XFCE4_VERSION}
CATEGORIES=	x11
COMMENT=	XFce4 trigger-launcher

.include "../../textproc/libxml2/buildlink3.mk"
.include "../../x11/xfce4-panel/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
