# $NetBSD: Makefile,v 1.2 2008/09/15 15:33:27 taca Exp $

DISTNAME=	cssmin-1.0.2
CATEGORIES=	www

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/rgrove/cssmin/
COMMENT=	Ruby library for minifying CSS
LICENSE=	modified-bsd

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
