# $NetBSD$
#

DISTNAME=	hicolor-icon-theme-0.4
CATEGORIES=	graphics
MASTER_SITES=	http://freedesktop.org/Software/icon-theme/releases/

MAINTAINER=	jmmv@NetBSD.org
HOMEPAGE=	http://freedesktop.org/Software/icon-theme
COMMENT=	Standard icon theme called hicolor

GNU_CONFIGURE=	YES
NO_BUILDLINK=	YES
NO_BUILD=	YES
USE_GNU_TOOLS+=	make
USE_LANGUAGES=	# empty

.include "../../mk/bsd.pkg.mk"
