# $NetBSD$

DISTNAME=	pst-math
PKGNAME=	tex-${DISTNAME}-0.61
TEXLIVE_REV=	20176

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Enhancement of PostScript math operators to use with pstricks

DEPENDS+=	tex-pstricks-[0-9]*:../../graphics/tex-pstricks

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
