# $NetBSD: Makefile,v 1.10 2012/09/15 10:03:37 obache Exp $
#

GST_PLUGINS1_NAME=	a52
GST_PLUGINS1_DIRS=	ext/a52dec

.include "../../multimedia/gst-plugins1-ugly/Makefile.common"

.include "../../audio/liba52/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
