# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
GUTENPRINT_LIB_BUILDLINK3_MK:=	${GUTENPRINT_LIB_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	gutenprint-lib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngutenprint-lib}
BUILDLINK_PACKAGES+=	gutenprint-lib
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}gutenprint-lib

.if ${GUTENPRINT_LIB_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.gutenprint-lib+=	gutenprint-lib>=5.0.1
BUILDLINK_PKGSRCDIR.gutenprint-lib?=	../../print/gutenprint-lib
.endif	# GUTENPRINT_LIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
