# $NetBSD: Makefile,v 1.3 2009/02/26 16:43:20 minskim Exp $
# TeX Live Revision 12181

DISTNAME=	bin-texlive
PKGNAME=	tex-${DISTNAME}-2008.12181

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Executables and files maintained as part of TeX Live

TEX_TEXMF_DIRS+=	${PREFIX}/share/texmf

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
