# $NetBSD: Makefile,v 1.1.1.1 2006/04/08 11:44:28 jmmv Exp $
#

GST_PLUGINS0.10_NAME=	dts
GST_PLUGINS0.10_DIRS=	ext/dts

.include "../../multimedia/gst-plugins0.10-bad/Makefile.common"

.include "../../audio/libdca/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
