# $NetBSD: Makefile,v 1.2 2009/04/24 06:13:31 minskim Exp $
# TeX Live Revision 15207

DISTNAME=	latex-fonts
PKGNAME=	tex-${DISTNAME}-2009
CATEGORIES=	fonts

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Collection of fonts used in LaTeX distributions

CONFLICTS+=	teTeX-texmf<=3.0nb12

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
