# $NetBSD: Makefile,v 1.3 2000/12/13 22:40:57 wiz Exp $
#

COMMENT=	Monetary, financial and related applications

SUBDIR+=	emma
SUBDIR+=	gnofin
SUBDIR+=	gnucash
SUBDIR+=	tclticker
SUBDIR+=	xfinans
SUBDIR+=	xinvest
SUBDIR+=	xquote

.include "../mk/bsd.pkg.subdir.mk"
