# $NetBSD$

BUILDLINK_TREE+=	SOPE

.if !defined(SOPE_BUILDLINK3_MK)
SOPE_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SOPE+=	SOPE>=2.0.0b1
BUILDLINK_ABI_DEPENDS.SOPE+=	SOPE>=2.0.0b1
BUILDLINK_PKGSRCDIR.SOPE?=	../../devel/SOPE
.endif # SOPE_BUILDLINK3_MK

BUILDLINK_TREE+=	-SOPE
