# $NetBSD$
# TeX Live Revision 15878

DISTNAME=	babelbib
PKGNAME=	tex-${DISTNAME}-1.29

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Multilingual bibliographies

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
