---
abstract: 'A library of commonly used type constraints'
author:
  - 'This distribution was extracted from the L<Reaction> code base by Guillermo'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Common
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.39
  MooseX::Types: 0.04
resources:
  IRC: irc://irc.perl.org/#moose
  license: http://dev.perl.org/licenses/
  repository: git://git.moose.perl.org/MooseX-Types-Common.git
version: 0.001002
