# $NetBSD: Makefile,v 1.3 2007/02/22 19:26:46 wiz Exp $
#

CATEGORIES=		math
MASTER_SITES=		${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		${R_HOMEPAGE_BASE}/sp/
COMMENT=		classes and methods for spatial data

R_PKGNAME=		sp
R_PKGVER=		0.9-26

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
