# $NetBSD: Makefile,v 1.76 2004/12/10 02:51:46 dogcow Exp $

DISTNAME=		estd-netbsd-r3
PKGNAME=		estd-0.3
CATEGORIES=		sysutils
MASTER_SITES=		http://www.elektro-eel.org/

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://www.elektro-eel.org/
COMMENT=		Dynamically sets the CPU-frequency on SpeedStep-enabled CPUs

ONLY_FOR_PLATFORM=	NetBSD-2.99.*-i386 NetBSD-[3-9]*-i386

WRKSRC=			${WRKDIR}/estd-r3

.include "../../mk/bsd.pkg.mk"
