# $NetBSD$

DISTNAME= 		phoenix-bin-acroread3-1.0

MAINTAINER=		kei@netbsd.org
COMMENT=		Acrobat Reader 3 plugin for phoenix-bin

DEPENDS+=		acroread5-5.[0-9]*:../../print/acroread
CONFLICTS+=		phoenix-bin-acroread-[0-9]*
CONFLICTS+=		phoenix-bin-acroread5-[0-9]*

ACROREAD=		Acrobat3

.include "../../www/phoenix-bin-acroread/Makefile.common"
