# $NetBSD$
# New ports collection makefile for:	libutf
# Version required:			2.10
# Date created:				Thu Oct 23 20:22:27 BST 1997
# Whom:					Alistair Crooks (agc@netbsd.org)
#

DISTNAME=	libutf-2.10
CATEGORIES=	misc
MASTER_SITES=	http://www.westley.demon.co.uk/src/

MAINTAINER=	agc@netbsd.org

MAN3=		ure.3 utf.3
GNU_CONFIGURE=	yes
ALL_TARGET=	tst

.include <bsd.port.mk>
