# $NetBSD$

DISTNAME=	prc
PKGNAME=	pdbar-0.5.1
CATEGORIES=	archivers
MASTER_SITES=	http://www.djw.org/product/palm/par/
EXTRACT_SUFX=	.tgz

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://www.djw.org/product/palm/par/
COMMENT=	Palm database archiver

PKG_INSTALLATION_TYPES=	overwrite pkgviews

NO_CONFIGURE=	yes
USE_BUILDLINK3=	yes

.include "../../mk/bsd.pkg.mk"
