# $NetBSD: Makefile,v 1.6 2004/08/10 14:27:17 taya Exp $

MOZILLA=	thunderbird-gtk1

COMMENT=	Mozilla mail client using the older GTK1 toolkit

.include "../../mail/thunderbird/Makefile-thunderbird.common"
