# $NetBSD: Makefile,v 1.5 2003/07/21 16:43:32 martti Exp $
#

DISTNAME=	libtar-1.2.11
CATEGORIES=	devel archivers
MASTER_SITES=	ftp://ftp-dev.cso.uiuc.edu/pub/libtar/

MAINTAINER=	seb@NetBSD.org
HOMEPAGE=	http://www-dev.cso.uiuc.edu/libtar/
COMMENT=	Library for manipulating POSIX tar files

GNU_CONFIGURE=		YES
USE_BUILDLINK3=		YES

.include "../../devel/zlib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
