# $NetBSD: Makefile,v 1.1.1.1 2010/02/09 18:53:01 minskim Exp $

DISTNAME=	dvipdfmx.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2010
TEXLIVE_REV=	18835

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-dvipdfmx

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
