# $NetBSD: Makefile,v 1.2 2008/06/22 16:10:51 taca Exp $

DISTNAME=	diff-lcs-1.1.2
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://rubyforge.org/projects/ruwiki/
COMMENT=	Diff library for Ruby
LICENSE=	gnu-gpl-v2 OR artistic OR ruby-license

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
