# $NetBSD: Makefile,v 1.3 2007/01/25 23:33:19 wiz Exp $
#

DISTNAME=	mutagen-1.10
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	audio
MASTER_SITES=	http://www.sacredchao.net/~piman/software/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.sacredchao.net/quodlibet/wiki/Development/Mutagen
COMMENT=	Audio metadata handling for Python

USE_LANGUAGES=	# none
PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
