# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBGAMIN_BUILDLINK3_MK:=	${LIBGAMIN_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libgamin
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibgamin}
BUILDLINK_PACKAGES+=	libgamin
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libgamin

.if ${LIBGAMIN_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libgamin+=	libgamin>=0.1.10
BUILDLINK_PKGSRCDIR.libgamin?=	../../sysutils/libgamin
.endif	# LIBGAMIN_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
