# $NetBSD: Makefile,v 1.9 2006/10/24 08:44:23 rillig Exp $

KOFFICE_LANGUAGE=	Slovenian
KOFFICE_LANGCODE=	sl
PKGREVISION=		5

DEPENDS+=	kdelibs-[0-9]*:../../x11/kdelibs3

.include "../../misc/koffice/i18n.mk"
.include "../../mk/bsd.pkg.mk"
