# $NetBSD$
#

GST_PLUGINS_NAME=	dvdread
GST_PLUGINS_DIR=	ext/dvdread

.include "../../multimedia/gst-plugins/Makefile.common"

.include "../../multimedia/libdvdread/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
