# $NetBSD: Makefile,v 1.2 2000/05/12 18:41:05 sakamoto Exp $
#

    SUBDIR += acroread-chsfont
    SUBDIR += acroread-chtfont
    SUBDIR += acroread-font-share
    SUBDIR += acroread-jpnfont
    SUBDIR += acroread-korfont
    SUBDIR += watanabe_vfont

.include "../mk/bsd.pkg.subdir.mk"
