# $NetBSD: Makefile,v 1.1.1.1 2010/07/05 14:46:25 taca Exp $
#

DIST_SUBDIR=	contao${CT_VER}-20101203

LICENSE=	gnu-lgpl-v3

.include "../../www/contao29/Makefile.version"
.include "../../www/contao/Makefile.example"
.include "../../www/contao/Makefile.common"
.include "../../lang/php/phpversion.mk"
.include "../../mk/bsd.pkg.mk"
