# $NetBSD: Makefile,v 1.2 2010/12/13 08:07:33 taca Exp $
#

LICENSE=	gnu-lgpl-v3

.include "../../www/contao29/Makefile.version"
.include "../../www/contao/Makefile.example"
.include "../../www/contao/Makefile.common"
.include "../../lang/php/phpversion.mk"
.include "../../mk/bsd.pkg.mk"
