# $NetBSD: Makefile,v 1.1.1.1 2001/10/21 22:50:01 mjl Exp $

DISTNAME=		ipa-1.2.5
CATEGORIES=		net sysutils
MASTER_SITES=		http://www.simon.org.ua/ipa/

MAINTAINER=		simon@simon.org.ua
HOMEPAGE=		http://www.simon.org.ua/ipa/
COMMENT=		IP accounting software

RESTRICTED=		"Needs to be built uniquely for each host"
NO_BIN_ON_FTP=		${RESTRICTED}
NO_BIN_ON_CDROM=	${RESTRICTED}
NO_PACKAGE=		${RESTRICTED}

ALL_TARGET=		NetBSD

.include "../../mk/bsd.pkg.mk"
