# $NetBSD$

DISTNAME=	hpijs-1.2.2
CATEGORIES=	print
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=hpinkjet/}

MAINTAINER=	jlam@netbsd.org
COMMENT=	HP inkjet printer driver server
HOMEPAGE=	http://hpinkjet.sourceforge.net/

USE_BUILDLINK2=		# defined
GNU_CONFIGURE=		# defined

.include "../../mk/bsd.pkg.mk"
