# $NetBSD$
# TeX Live Revision 1

DISTNAME=	kotex-base.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.1.1
MASTER_SITES=	http://ftp.ktug.or.kr/KTUG/texlive/2008/archive/

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://project.ktug.or.kr/ko.TeX/
COMMENT=	Documentation for tex-kotex-base

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
