# $NetBSD: Makefile,v 1.2 2001/02/17 17:54:49 wiz Exp $
#

DISTNAME=	newsfetch-1.3
CATEGORIES=	news
MASTER_SITES=	${MASTER_SITE_LOCAL}

MAINTAINER=	jrf@diverge.org
HOMEPAGE=	# doesn't work anymore - http://www.diverge.org/jrf/
COMMENT=	Downloads newsgroup messages in mail file format

USE_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/newsfetch

.include "../../mk/bsd.pkg.mk"
