# $NetBSD$

BUILDLINK_DEPMETHOD.darts?=	build

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DARTS_BUILDLINK3_MK:=	${DARTS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	darts
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndarts}
BUILDLINK_PACKAGES+=	darts

.if !empty(DARTS_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.darts+=	darts>=0.2
BUILDLINK_PKGSRCDIR.darts?=	../../textproc/darts
.endif	# DARTS_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
