# $NetBSD$
# TeX Live Revision 17431

DISTNAME=	magaz.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.2

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-magaz

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
