# $NetBSD$
# TeX Live Revision 8177

DISTNAME=	euenc
PKGNAME=	tex-${DISTNAME}-0.1d

MAINTAINER=	minskim@NetBSD.org
COMMENT=	LaTeX font encoding based on unicode

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
