# $NetBSD$

DISTNAME=	DB-1.7.6
CATEGORIES=	databases

MAINTAINER=	adrianp@NetBSD.org
HOMEPAGE= 	http://pear.php.net/package/DB
COMMENT=	PHP Database Abstraction Layer

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
