# $NetBSD: Makefile,v 1.2 2006/02/05 23:08:33 joerg Exp $

DISTNAME=	DB-1.7.6
CATEGORIES=	databases

CONFLICTS=	php-pear-DB-[0-9]

MAINTAINER=	adrianp@NetBSD.org
HOMEPAGE= 	http://pear.php.net/package/DB
COMMENT=	PHP Database Abstraction Layer

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
