# $NetBSD: Makefile,v 1.17 2009/01/01 21:47:31 hubertf Exp $
#

DISTNAME=		cmus-2.2.0
PKGREVISION=		6
CATEGORIES=		audio
MASTER_SITES=		http://mirror.greaterscope.net/cmus/
EXTRACT_SUFX=		.tar.bz2

MAINTAINER=		ahoka@NetBSD.org
HOMEPAGE=		http://cmus.sourceforge.net/
COMMENT=		Cmus is a curses based music player with a lot of features

CONFLICTS+=		cmus-unofficial-[0-9]*

.include "../cmus/Makefile.common"
