# $NetBSD: Makefile,v 1.3 1998/03/26 10:14:26 hubertf Exp $
# FreeBSD Id: Makefile,v 1.9 1997/10/13 05:11:40 jmacd Exp
#

DISTNAME= 	prcs-1.2.3
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.xcf.berkeley.edu/pub/prcs/

MAINTAINER=	jmacd@FreeBSD.ORG

GNU_CONFIGURE=	yes
MAN1=		prcs.1

.include "../../mk/bsd.pkg.mk"
