# $NetBSD: Makefile,v 1.2 2010/05/07 08:34:23 ahoka Exp $

DISTNAME=	plist-3.1.0
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://plist.rubyforge.org/
COMMENT=	Manipulate Property List files
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
