# $NetBSD: Makefile,v 1.2 2002/04/14 11:34:20 schmonz Exp $
#

.include "Makefile.common"

COMMENT+=		, tty version

USE_BUILDLINK2=		# defined

ALL_TARGET=		ce
INSTALL_TARGET=		install man-install

.include "../../devel/ncurses/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
