# $NetBSD: Makefile,v 1.1.1.1 2002/04/08 19:59:08 schmonz Exp $
#

.include "Makefile.common"

COMMENT+=		, tty version

USE_BUILDLINK_ONLY=	# defined

ALL_TARGET=		ce
INSTALL_TARGET=		install man-install

.include "../../devel/ncurses/buildlink.mk"
.include "../../mk/bsd.pkg.mk"
