# $NetBSD: Makefile,v 1.4 2011/01/21 17:32:29 minskim Exp $

DISTNAME=	fontspec.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.1f
TEXLIVE_REV=	21527

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-fontspec

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
