# $NetBSD: Makefile,v 1.1.1.1 2009/07/21 07:24:53 minskim Exp $

DISTNAME=	fontspec.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.18
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-fontspec

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
