# $NetBSD: Makefile,v 1.9 2006/10/24 08:44:22 rillig Exp $

KOFFICE_LANGUAGE=	Czech
KOFFICE_LANGCODE=	cs
PKGREVISION=		5

DEPENDS+=	koffice-[0-9]*:../../misc/koffice

.include "../../misc/koffice/i18n.mk"
.include "../../mk/bsd.pkg.mk"
