#!/bin/sh
# $NetBSD: pre-install,v 1.2 1999/02/28 15:39:09 hwr Exp $

cd ${WRKSRC}
cp p_port.h ${LOCALBASE}/include
cp pdf.h ${LOCALBASE}/include
cp libpdf.a ${LOCALBASE}/lib
mkdir ${LOCALBASE}/share/afm
cp fonts/*.afm ${LOCALBASE}/share/afm/
cp fonts/afmlist ${LOCALBASE}/share/afm/
cp text2pdf ${LOCALBASE}/bin
