# $NetBSD: Makefile,v 1.6 2006/02/05 23:11:10 joerg Exp $

DISTNAME=	Date-1.4.3
CATEGORIES=	time

MAINTAINER=	jdolecek@NetBSD.org
COMMENT=	PHP Date and Time Zone Classes

CONFLICTS=	php-pear-Date-[0-9]

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
