# $NetBSD: Makefile,v 1.4 2004/11/27 10:02:52 jdolecek Exp $

DISTNAME=	Date-1.4.3
CATEGORIES=	time

MAINTAINER=	jdolecek@NetBSD.org
COMMENT=	PHP Date and Time Zone Classes

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
