# $NetBSD: Makefile,v 1.8 2012/03/18 02:44:18 taca Exp $

DISTNAME=	ferret-0.11.8.5
CATEGORIES=	textproc

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/jkraemer/ferret/
COMMENT=	Text search engine library written for Ruby
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
