# $NetBSD: Makefile,v 1.1.1.1 2009/07/09 22:56:21 minskim Exp $

DISTNAME=	footmisc.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-5.5a
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-footmisc

CONFLICTS+=	teTeX-texmf<=3.0nb17

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
