# $NetBSD$
# TeX Live Revision 17020

DISTNAME=	a5comb
PKGNAME=	tex-${DISTNAME}-4

MAINTAINER=	minskim@NetBSD.org
COMMENT=	A5 paper sizes support for LaTeX

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
