# $NetBSD$
#

DISTNAME=	xlupe-1.1
CATEGORIES=	x11
MASTER_SITES=	http://core.de/~coto/xlupe/

MAINTAINER=	coto@core.de
HOMEPAGE=	http://core.de/~coto/xlupe/
COMMENT=	magnifier for X

USE_IMAKE=	yes
USE_XPM=	yes

.include "../../mk/bsd.pkg.mk"
