# $NetBSD$

DISTNAME=	kastrup
PKGNAME=	tex-${DISTNAME}-2010
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Expansible conversion into binary-based number systems

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
