# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SKEY_BUILDLINK3_MK:=	${SKEY_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	skey
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nskey}
BUILDLINK_PACKAGES+=	skey

.if !empty(SKEY_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.skey+=	skey>=1.1.5
BUILDLINK_PKGSRCDIR.skey?=	../../security/skey
.endif	# SKEY_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
