# $NetBSD: buildlink3.mk,v 1.1 2004/02/15 20:01:11 wiz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FRIBIDI_BUILDLINK3_MK:=	${FRIBIDI_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	fribidi
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfribidi}
BUILDLINK_PACKAGES+=	fribidi

.if !empty(FRIBIDI_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.fribidi+=	fribidi>=0.10.4
BUILDLINK_PKGSRCDIR.fribidi?=	../../converters/fribidi
.endif	# FRIBIDI_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
