# $NetBSD$
# TeX Live Revision 10804

DISTNAME=	IEEEtran.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.7a

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-IEEEtran

CONFLICTS+=	tex-IEEEtran<=1.7nb1

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
