# $NetBSD: Makefile,v 1.2 2009/06/09 23:00:02 minskim Exp $

DISTNAME=	hyperref.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-6.80x
TEXLIVE_REV=	17902

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-hyperref

CONFLICTS+=	teTeX-texmf<=3.0nb15

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
