# $NetBSD$
#

DISTNAME=	pure-ftpd-1.0.9
CATEGORIES=	net
MASTER_SITES=	http://prdownloads.sourceforge.net/pureftpd/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	dawszy@arhea.net
HOMEPAGE=	http://www.pureftpd.org/
COMMENT=	ftpd daemon with builtin SQL support

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
