# $NetBSD: Makefile,v 1.3 1998/04/15 10:38:19 agc Exp $

DISTNAME=	bison-1.25
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GNU}

MAINTAINER=	thorpej@netbsd.org

GNU_CONFIGURE=	yes
MAN1=		bison.1
INFO_FILES=	bison

.include "../../mk/bsd.pkg.mk"
