# $NetBSD: Makefile,v 1.1 2008/01/21 11:08:33 ichiro Exp $
#

DISTNAME=	cut-2.4
PKGNAME=	cut-2
PKGREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	http://www.falvotech.com/content/cut/downloads/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.falvotech.com/content/cut/
COMMENT=	C Unit Tester

PKG_DESTDIR_SUPPORT=	user-destdir

INSTALLATION_DIRS+=	bin

WRKSRC=	${WRKDIR}/repo

#BUILD_TARGET=	bin/cutgen
.include "../../mk/bsd.pkg.mk"
