# $NetBSD$

R_PKGNAME=	nlme
R_PKGVER=	3.1-23

MAINTAINER=	markd@netbsd.org
COMMENT=	Linear and nonlinear mixed effects models

PLIST_SRC=	/dev/null

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
