# $NetBSD$
# TeX Live Revision 16857

DISTNAME=	ifluatex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.2

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-ifluatex

CONFLICTS+=	tex-oberdiek-doc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
