# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBDATRIE_BUILDLINK3_MK:=	${LIBDATRIE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libdatrie
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdatrie}
BUILDLINK_PACKAGES+=	libdatrie
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libdatrie

.if ${LIBDATRIE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libdatrie+=	libdatrie>=0.1.3
BUILDLINK_PKGSRCDIR.libdatrie?=	../../devel/libdatrie
.endif	# LIBDATRIE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
