# $NetBSD: Makefile,v 1.52 2007/02/04 20:55:23 dmcmahill Exp $
#

PKGNAME=	w3m-${W3M_VERS}
COMMENT=	Multilingualized version of a pager/text-based browser w3m

CONFLICTS+=	w3m-img-[0-9]*

.include "../../www/w3m/Makefile.common"
