# $NetBSD$
# TeX Live Revision 12557

DISTNAME=	rotating.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.16a

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-rotating

CONFLICTS+=	teTeX-texmf<=3.0nb13

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
