# $NetBSD$

DISTNAME=	parseconfig-0.5.2
CATEGORIES=	devel

MAINTAINER=	taca@NetBSD.org
HOMEPAGE=	http://www.5dollarwhitebox.org/
COMMENT=	Provides simple parsing of standard *nix style config files
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
