# $NetBSD$
#

DISTNAME=		exiv2-0.6.1
CATEGORIES=		graphics
MASTER_SITES=		http://home.arcor.de/ahuggel/exiv2/

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://home.arcor.de/ahuggel/exiv2/
COMMENT=		Image metadata manipulation

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes
USE_GNU_TOOLS+=		make

.include "../../mk/bsd.pkg.mk"
