# $NetBSD: Makefile,v 1.2 2008/04/04 15:30:01 jlam Exp $

DISTNAME=	simple-rss-1.2.3
CATEGORIES=	textproc

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://github.com/cardmagic/simple-rss
COMMENT=	Simple, flexible, extensible, and liberal RSS and Atom reader
LICENSE=	gnu-lgpl-v2.1

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
