# $NetBSD: Makefile,v 1.1.1.1 2009/07/07 22:23:07 minskim Exp $
# TeX Live Revision 15878

DISTNAME=	xunicode
PKGNAME=	tex-${DISTNAME}-0.91

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Generate Unicode characters from accented glyphs

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
