# $NetBSD$

DISTNAME=	wmMoonClock-1.27
CATEGORIES=	x11
MASTER_SITES=	http://nis-www.lanl.gov/~mgh/WindowMaker/

MAINTAINER=	jens
HOMEPAGE=	http://nis-www.lanl.gov/~mgh/WindowMaker/DockApps.shtml

USE_GMAKE=	YES
USE_X11BASE=	YES
WRKSRC=         ${WRKDIR}/${DISTNAME}/Src

.include "../../mk/bsd.pkg.mk"
