# $NetBSD$
# TeX Live Revision 17087

DISTNAME=	boxedminipage.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2009

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-boxedminipage

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
