# $NetBSD: Makefile,v 1.13 2006/01/24 07:32:20 wiz Exp $

MOZILLA=		thunderbird

COMMENT=		Mozilla mail client

_MOZILLA_USE_GTK2=	# yes
MOZILLA_USE_XFT=	YES

.include "../../mail/thunderbird/Makefile-thunderbird.common"
.include "../../mk/bsd.pkg.mk"
