# $NetBSD: Makefile,v 1.5 2004/08/10 14:27:17 taya Exp $

MOZILLA=	thunderbird

COMMENT=	Mozilla mail client

MOZILLA_USE_GTK2=	# defined
MOZILLA_USE_XFT=	YES

.include "../../mail/thunderbird/Makefile-thunderbird.common"
