# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FUSEFS_BUILDLINK3_MK:=	${FUSEFS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	fusefs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfusefs}
BUILDLINK_PACKAGES+=	fusefs
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}fusefs

.if ${FUSEFS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.fusefs+=	fusefs>=2.5.2
BUILDLINK_PKGSRCDIR.fusefs?=	../../filesystems/fuse
.endif	# FUSEFS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
