# $NetBSD: Makefile,v 1.2 2001/12/21 10:52:30 agc Exp $

DISTNAME=	asp2php-0.76.10
PKGNAME=	gtk${DISTNAME}
CATEGORIES=	www
MASTER_SITES=	http://65.108.58.129/asp2php/

MAINTAINER=	shell@netbsd.org
HOMEPAGE=	http://asp2php.naken.cc/
COMMENT=	gtk+ version of utility to convert asp pages to php pages

ALL_TARGET=	all gui

.include "../../x11/gtk/buildlink.mk"
.include "../../mk/bsd.pkg.mk"
