# $NetBSD: Makefile,v 1.60 2002/05/05 13:13:15 wiz Exp $
#

DISTNAME=		libargparse-0.1.0000
CATEGORIES=		devel
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=aqsis/}

MAINTAINER=		packages@netbsd.org
HOMEPAGE=		http://www.aqsis.org/
COMMENT=		argument parsing library in C++

GNU_CONFIGURE=		yes
USE_LIBTOOL=		yes
LTCONFIG_OVERRIDE=	${WRKSRC}/ltconfig

.include "../../mk/bsd.pkg.mk"
