# $NetBSD$

DISTNAME=	asyfig.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.1c
TEXLIVE_REV=	17512

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-asyfig

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
