# $NetBSD: Makefile,v 1.7 1998/08/20 15:17:38 tsarna Exp $
#

DISTNAME=	unclutter-8
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	utilities
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	mycroft@netbsd.org

WRKSRC=		${WRKDIR}/unclutter
USE_IMAKE=	yes

.include "../../mk/bsd.pkg.mk"
