# $NetBSD$

DISTNAME=	pst-poly.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.61
TEXLIVE_REV=	16460

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-pst-poly

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
