# $NetBSD$
# TeX Live Revision 16864

DISTNAME=	url
PKGNAME=	tex-${DISTNAME}-3.2

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Verbatim with URL-sensitive line breaks

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
