# $NetBSD: Makefile,v 1.3 2011/01/20 16:23:59 minskim Exp $

DISTNAME=	chessfss.doc
PKGNAME=        tex-${DISTNAME:S/./-/}-1.2a
TEXLIVE_REV=	19440

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-chessfss

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
