# $NetBSD: Makefile,v 1.5 2009/08/26 19:57:44 sno Exp $

DISTNAME=	jpegoptim-1.2.3
CATEGORIES=	graphics
MASTER_SITES=	http://www.kokkonen.net/tjko/src/

MAINTAINER=	fab@gnux.info
HOMEPAGE=	http://www.kokkonen.net/tjko/projects.html
COMMENT=	JPEG optimizer

PKG_DESTDIR_SUPPORT=	user-destdir
GNU_CONFIGURE=		YES

.include "../../graphics/jpeg/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
