# $NetBSD$

.include "../../meta-pkgs/xfce4/Makefile.common"

XFCE4_VERSION=	0.2

DISTNAME=	xfce4-datetime-plugin-${XFCE4_VERSION}
CATEGORIES=	sysutils
MASTER_SITES=	http://download.berlios.de/xfce-goodies/
COMMENT=	XFce4 calendar plugin

.include "../../x11/xfce4-panel/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
