# $NetBSD: Makefile,v 1.2 2007/02/19 21:52:43 joerg Exp $

WBM_NAME=	useradmin

COMMENT=	Webmin module to manage users and groups

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
