# $NetBSD$
#

DISTNAME=	imwheel-0.9.9
CATEGORIES=	x11
MASTER_SITES=	http://jonatkins.org/imwheel/files/

MAINTAINER=	zuntum@netbsd.org
HOMEPAGE=	http://jcatki.dhs.org/imwheel/
COMMENT=	tool which helps to use mousewheels

GNU_CONFIGURE=	YES
USE_X11BASE=	YES

CONFIGURE_ARGS+=--disable-gpm

.include "../../mk/bsd.pkg.mk"
