# $NetBSD: buildlink3.mk,v 1.10 2008/01/18 05:06:37 tnn Exp $

BUILDLINK_TREE+=	GLXKit

.if !defined(GLXKIT_BUILDLINK3_MK)
GLXKIT_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.GLXKit+=	GLXKit>=0.3.1r2nb3
BUILDLINK_ABI_DEPENDS.GLXKit?=	GLXKit>=0.3.1r2nb12
BUILDLINK_PKGSRCDIR.GLXKit?=	../../graphics/GLXKit

.include "../../graphics/RenderKit/buildlink3.mk"
.endif # GLXKIT_BUILDLINK3_MK

BUILDLINK_TREE+=	-GLXKit
