# $NetBSD$
# TeX Live Revision 7340

DISTNAME=	preprint.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2008.7340

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-preprint

CONFLICTS+=	teTeX-texmf<=3.0nb16

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
