# $NetBSD$
# TeX Live Revision 16044

DISTNAME=	dvipng.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.12

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for dvipng

CONFLICTS+=	dvipng<1.12

INFO_FILES=	yes

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
