#!/bin/sh
#
# $NetBSD: INSTALL,v 1.1 2001/10/31 22:58:46 zuntum Exp $

SAMBA_PRIVATE="@SAMBA_PRIVATE@"

case ${STAGE} in
POST-INSTALL)
	# Create SMB password file
	if [ ! -e ${SAMBA_PRIVATE}/smbpasswd ]
	then
		${ECHO} -n "Creating ${SAMBA_PRIVATE}/smbpasswd..."
		${CHOWN} -R 0:0 ${SAMBA_PRIVATE}
		${CAT} /etc/passwd | ${PKG_PREFIX}/sbin/mksmbpasswd	\
			> ${SAMBA_PRIVATE}/smbpasswd
		${CHMOD} 600 ${SAMBA_PRIVATE}/smbpasswd
		${CHMOD} 500 ${SAMBA_PRIVATE}
		echo "done."
	fi
	;;
esac
