# $NetBSD$
#

DISTNAME=	HUnit-1.1.20060515
CATEGORIES=	devel

MAINTAINER=	jmmv@NetBSD.org
COMMENT=	Unit testing framework for Haskell
HOMEPAGE=	http://hunit.sourceforge.net/

.include "../../lang/hugs/package.mk"
.include "../../mk/bsd.pkg.mk"
