# $NetBSD: Makefile,v 1.2 2002/07/22 00:13:14 schmonz Exp $
#

DISTNAME=	cvsps-1.3.2
CATEGORIES=	devel
MASTER_SITES=	${HOMEPAGE}

MAINTAINER=	schmonz@netbsd.org
HOMEPAGE=	http://www.cobite.com/cvsps/
COMMENT=	generates 'patchset' information from a CVS repository

USE_GMAKE=	# defined

ALL_TARGET=	cvsps

.include "../../mk/bsd.pkg.mk"
