# $NetBSD: Makefile,v 1.1.1.1 2004/04/16 13:27:32 jmmv Exp $
#

GST_PLUGINS_NAME=	mad
GST_PLUGINS_DIR=	ext/mad

.include "../../multimedia/gst-plugins/Makefile.common"

.include "../../audio/libid3tag/buildlink3.mk"
.include "../../audio/libmad/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
