# $NetBSD: Makefile,v 1.2 2009/04/22 11:42:01 seb Exp $

DISTNAME=	netaddr-1.5.0
#PKGREVISION=	1
CATEGORIES=	net

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://netaddr.rubyforge.org/
COMMENT=	Ruby package for working with network addresses
LICENSE=	gnu-gpl-v2 OR ruby-license

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
