# $NetBSD$

R_PKGNAME=	rpart
R_PKGVER=	3.1-5

MAINTAINER=	markd@netbsd.org
COMMENT=	Recursive partitioning

PLIST_SRC=	/dev/null

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
