#!/bin/sh
#
# $NetBSD: INSTALL,v 1.2 2001/11/24 20:49:42 jlam Exp $

case ${STAGE} in
POST-INSTALL)
	${CAT} << EOF
===========================================================================
Please also refer to:

	${PKG_PREFIX}/share/doc/html/cyrus-imapd/install.html

for more detailed instructions on setting up the environment before
starting the Cyrus IMAP server.  In particular, several services will
probably need to be added to /etc/services.
===========================================================================
EOF
	;;
esac
