#!/bin/sh
#
# $NetBSD: INSTALL,v 1.1 2001/11/01 00:59:46 zuntum Exp $

case ${STAGE} in
POST-INSTALL)
	${CAT} << EOF
===========================================================================
Please also refer to:

	${PKG_PREFIX}/share/doc/html/cyrus-imapd/install.html

to set up the necessary directories before starting the Cyrus IMAP server.
===========================================================================
EOF
	;;
esac
