# $NetBSD: Makefile,v 1.2 2000/11/11 14:50:57 tron Exp $
#

DISTNAME=	fastjar-0.90
CATEGORIES=	archivers
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=fastjar/}
EXTRACT_SUFX=	.tgz

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://fastjar.sourceforge.net/
COMMENT=	C language version of the 'jar' archiver normally used by Java

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
