# $NetBSD: Makefile,v 1.1.1.1 2000/02/01 16:41:05 rh Exp $
#

DISTNAME=	fastjar-0.90
CATEGORIES=	archivers
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=fastjar/}
EXTRACT_SUFX=	.tgz

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://fastjar.sourceforge.net/

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
