# $NetBSD$

DISTNAME=	little-plugger-1.1.2
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://gemcutter.org/gems/little-plugger
COMMENT=	Module that provides Gem based plugin management
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
