# $NetBSD$
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBCDIO_BUILDLINK3_MK:=	${LIBCDIO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libcdio
.endif

.if !empty(LIBCDIO_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=			libcdio
BUILDLINK_DEPENDS.libcdio?=		libcdio>=0.65
BUILDLINK_PKGSRCDIR.libcdio?=		../../misc/libcdio.work

.endif # LIBCDIO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
