# $NetBSD: Makefile,v 1.12 2006/09/09 02:41:55 obache Exp $

DISTNAME=	ish-1.11
CATEGORIES=	converters
MASTER_SITES=	ftp://ports.jp.freebsd.org/pub/FreeBSD-jp/ports-jp/LOCAL_PORTS/

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Binary-to-text file-encoder

PKG_DESTDIR_SUPPORT=	user-destdir

INSTALLATION_DIRS=	bin
MAKE_FILE=	makefile
BUILD_TARGET=	ish

.include "../../mk/bsd.pkg.mk"
