# $NetBSD$
#

DISTNAME=	hsetroot-1.0.2
CATEGORIES=	x11
MASTER_SITES=	http://thegraveyard.org/files/

MAINTAINER=	lems@gmx.net
HOMEPAGE=	http://thegraveyard.org/hsetroot.php
COMMENT=	Allows you to compose wallpapers for X

GNU_CONFIGURE=	yes
USE_X11=	yes

.include "../../graphics/imlib2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
