# $NetBSD$

DISTNAME=	soauth-0.2
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	security

MAINTAINER=	obache@NetBSD.org
HOMEPAGE=	http://github.com/tofumatt/soauth
COMMENT=	Ruby library that creates HTTP headers for OAuth Authorization
LICENSE=	mit

GEM_BUILD=	gemspec

.include "../../misc/rubygems/rubygem.mk"
.include "../../mk/bsd.pkg.mk"
