# $NetBSD$

DISTNAME=	ocr-b.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2011
TEXLIVE_REV=	20852

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Documentation for tex-ocr-b

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
