# $NetBSD: buildlink3.mk,v 1.13 2004/02/18 16:35:27 jlam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
BINUTILS_BUILDLINK3_MK:=	${BINUTILS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	binutils
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbinutils}
BUILDLINK_PACKAGES+=	binutils

.if !empty(BINUTILS_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.binutils+=		binutils>=2.14.0
BUILDLINK_PKGSRCDIR.binutils?=		../../devel/binutils
BUILDLINK_DEPMETHOD.binutils?=		build
.endif	# BINUTILS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
