# $NetBSD: Makefile.common,v 1.3 2005/09/05 15:00:09 taya Exp $

ANTHY_VERSION=	6700b
DISTNAME=	anthy-${ANTHY_VERSION}
CATEGORIES=	inputmethod
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE_JP:=anthy/15414/}
DISTFILES=	${DISTNAME}.tar.gz

DISTINFO_FILE=	${.CURDIR}/../../inputmethod/anthy/distinfo
PATCHDIR=	${.CURDIR}/../../inputmethod/anthy/patches

HOMEPAGE=	http://anthy.sourceforge.jp/
