# $NetBSD$

DISTNAME=	merb_param_protection-0.9.2
PKGNAME=	${DISTNAME:S/_/-/g}
CATEGORIES=	www

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.merbivore.com/
COMMENT=	Merb plugin supplying methods to filter parameters

DEPENDS+=	merb-core>=0.9.2:../../www/merb-core

.include "../../misc/rubygems/rubygem.mk"
.include "../../mk/bsd.pkg.mk"
