# $NetBSD: Makefile,v 1.8 2005/06/01 18:03:26 jlam Exp $
#

DISTNAME=	wmi-10
CATEGORIES=	wm
MASTER_SITES=	http://wmii.de/download/

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://wmii.de/
COMMENT=	Minimalist, flexible and highly customizable window manager

USE_LANGUAGES=	c c++
GNU_CONFIGURE=	yes

.include "../../fonts/Xft2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
