# $NetBSD: Makefile,v 1.9 2003/07/21 16:49:36 martti Exp $

DISTNAME=	cgoban-1.9.12
CATEGORIES=	games
MASTER_SITES=	http://www.igoweb.org/~wms/comp/cgoban/

MAINTAINER=	bad@NetBSD.org
HOMEPAGE=	http://www.igoweb.org/~wms/comp/cgoban/index.html
COMMENT=	The complete goban.  A Go server client and sgf viewer/editor

GNU_CONFIGURE=	yes

.include "../../mk/x11.buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
