#!/bin/sh
#
#	$NetBSD: soffice,v 1.2 2005/10/10 20:08:49 mrauch Exp $
#
SOINST=@@PREFIX@@/openoffice.org@@OO_VER@@

# make sure we can find `whoami` on solaris
PATH=${PATH}:/usr/ucb

# add the chosen java directory to $PATH to allow OOo to
# automatically find it
PATH=${PATH}:@@JAVA_HOME@@

# default data seg size is too small for java
ulimit -d `ulimit -H -d`

exec ${SOINST}/program/soffice "$@"
