# $NetBSD$
#

DISTNAME=		srm-1.2.8
CATEGORIES=		security
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=srm/}

MAINTAINER=		cube@NetBSD.org
HOMEPAGE=		http://srm.sourceforge.net/
COMMENT=		Secure replacement for rm(1)

USE_BUILDLINK3=		yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
