# $NetBSD$

DISTNAME=	speyes-1.2.0
CATEGORIES=	x11
MASTER_SITES=	http://www.halcyon.com/amalmin/speyes/

MAINTAINER=	jlam@netbsd.org
HOMEPAGE=	http://www.halcyon.com/amalmin/speyes/speyes.html

DEPENDS+=	xpm-*:../../graphics/xpm

USE_X11BASE=	yes
USE_IMAKE=	yes

.include "../../mk/bsd.pkg.mk"
