# $NetBSD: Makefile,v 1.18 2006/03/04 21:29:06 jlam Exp $

DISTNAME=	mpack-1.6
CATEGORIES=	converters mail news
MASTER_SITES=	ftp://ftp.andrew.cmu.edu/pub/mpack/

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	External MIME packer/unpacker

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
