# $NetBSD: Makefile,v 1.2 2008/04/17 17:23:24 jlam Exp $

DISTNAME=	columnize-0.3.1
PKGREVISION=	1
CATEGORIES=	misc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://rubyforge.org/projects/rocky-hacks/columnize
COMMENT=	Ruby module to print an Array in column-sorted order
LICENSE=	gnu-gpl-v2

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
