# $NetBSD: Makefile,v 1.7 2004/12/03 15:15:06 wiz Exp $
#

DISTNAME=	error-0.0
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.gw.com/pub/people/christos/

MAINTAINER=	christos@netbsd.org
COMMENT=	Insert compiler errors in source files as comments

.include "../../mk/bsd.prefs.mk"

.include "../../mk/bsd.pkg.mk"
