# $NetBSD$

DISTNAME=	pst-gr3d.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.34
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-pst-gr3d

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
