# $NetBSD$
#

DISTNAME=       vcdimager-0.6.2
CATEGORIES=	sysutils
MASTER_SITES=   ${MASTER_SITE_GNU:=vcdimager/}

MAINTAINER=	collver@linuxfreemail.com
HOMEPAGE=	http://www.gnu.org/software/vcdimager/
COMMENT=	mastering suite for Video CDs

USE_BUILDLINK_ONLY=	YES
#USE_GTEXINFO=		YES
USE_GMAKE=		YES
GNU_CONFIGURE=		YES

.include "../../devel/gettext-lib/buildlink.mk"
.include "../../mk/bsd.pkg.mk"
