# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ILMBASE_BUILDLINK3_MK:=	${ILMBASE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	ilmbase
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nilmbase}
BUILDLINK_PACKAGES+=	ilmbase
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ilmbase

.if ${ILMBASE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.ilmbase+=	ilmbase>=1.0.1
BUILDLINK_PKGSRCDIR.ilmbase?=	../../graphics/ilmbase
.endif	# ILMBASE_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
