# $NetBSD: $
#

DISTNAME=       usbutil-0.1
CATEGORIES=	sysutils
MASTER_SITES=   ftp://ftp.augustsson.net/pub/netbsd/

MAINTAINER=	lennart@augustsson.net

.include "../../mk/bsd.prefs.mk"

.include "../../mk/bsd.pkg.mk"
