# $NetBSD: Makefile,v 1.1.1.1 2008/04/04 15:17:43 jlam Exp $

DISTNAME=	logging-1.4.3
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://rubygems.org/gems/logging
COMMENT=	Flexible logging library for Ruby based on log4j
LICENSE=	ruby-license

DEPENDS+=	${RUBY_PKGPREFIX}-little-plugger>=1.1.2:../../devel/ruby-little-plugger

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
