# $NetBSD: Makefile,v 1.2 2010/09/10 13:51:45 taca Exp $

DISTNAME=	logging-1.7.2
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://rubygems.org/gems/logging
COMMENT=	Flexible logging library for Ruby based on log4j
LICENSE=	ruby-license

DEPENDS+=	${RUBY_PKGPREFIX}-little-plugger>=1.1.3:../../devel/ruby-little-plugger

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
