# $NetBSD: Makefile,v 1.1 2002/05/31 11:53:40 seb Exp $
#

COMMENT=	Input method tools and libraries

SUBDIR+=	canna-lib
SUBDIR+=	canna-server
SUBDIR+=	canuum
SUBDIR+=	ja-freewnn-lib
SUBDIR+=	ja-freewnn-server
SUBDIR+=	kinput2
SUBDIR+=	sj3-lib
SUBDIR+=	sj3-server
SUBDIR+=	skkfep
SUBDIR+=	skkinput
SUBDIR+=	skkserv

.include "../mk/bsd.pkg.subdir.mk"
