# $NetBSD: Makefile,v 1.4 2002/06/04 08:47:45 uebayasi Exp $
#

COMMENT=	Input method tools and libraries

SUBDIR+=	canna-dict
SUBDIR+=	canna-lib
SUBDIR+=	canna-server
SUBDIR+=	canna-server-bin
SUBDIR+=	canuum
SUBDIR+=	ja-freewnn-dict
SUBDIR+=	ja-freewnn-lib
SUBDIR+=	ja-freewnn-server
SUBDIR+=	ja-freewnn-server-bin
SUBDIR+=	kinput2
SUBDIR+=	libtabe
SUBDIR+=	sj3-dict
SUBDIR+=	sj3-lib
SUBDIR+=	sj3-server
SUBDIR+=	sj3-server-bin
SUBDIR+=	skkfep
SUBDIR+=	skkinput
SUBDIR+=	skkserv
SUBDIR+=	xcin

.include "../mk/bsd.pkg.subdir.mk"
