# $NetBSD$
#

    SUBDIR += asclock
    SUBDIR += asclock-gtk
    SUBDIR += asclock-xlib
    SUBDIR += cal
    SUBDIR += cardboard-schedule
    SUBDIR += catclock
    SUBDIR += dclock
    SUBDIR += emiclock
    SUBDIR += glclock
    SUBDIR += ical
    SUBDIR += logtime
    SUBDIR += plan
    SUBDIR += polclock
    SUBDIR += py-mxDateTime
    SUBDIR += rclock
    SUBDIR += remind
    SUBDIR += sunclock
    SUBDIR += swisswatch
    SUBDIR += titrax
    SUBDIR += wmcalclock
    SUBDIR += wmmoonclock
    SUBDIR += wmtime
    SUBDIR += xbeats
    SUBDIR += xcal
    SUBDIR += xdaliclock
    SUBDIR += xtimer

.include "../mk/bsd.pkg.subdir.mk"
