# $NetBSD: Makefile,v 1.1.1.1 2009/07/18 23:33:56 minskim Exp $

DISTNAME=	acmtrans
PKGNAME=	tex-${DISTNAME}-2008.7340
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Class and BibTeX style for ACM Transactions

DEPENDS+=	tex-latex-[0-9]*:../../print/tex-latex

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
