# $NetBSD: Makefile,v 1.1 2006/03/14 22:58:47 christos Exp $
#

DISTNAME=	sup-0.0
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.astron.com/pub/sup/

MAINTAINER=	christos@NetBSD.org
COMMENT=	Network file distribution/synchronisation utility

INSTALLATION_DIRS_FROM_PLIST=yes

.include "../../mk/bsd.pkg.mk"
