# $NetBSD: Makefile,v 1.6 2008/05/30 14:25:26 christos Exp $
#

DISTNAME=	sup-0.3
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.astron.com/pub/sup/

MAINTAINER=	christos@NetBSD.org
COMMENT=	Network file distribution/synchronisation utility

PKG_DESTDIR_SUPPORT=	user-destdir

INSTALLATION_DIRS+=	sbin ${PKGMANDIR}/man1 ${PKGMANDIR}/man8

.include "../../mk/bsd.pkg.mk"
