# $NetBSD$

DISTNAME=	endfloat.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.4i
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-endfloat

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
