# $NetBSD: Makefile,v 1.1.1.1 2010/04/16 17:34:54 minskim Exp $

DISTNAME=	cases
PKGNAME=	tex-${DISTNAME}-2.5
TEXLIVE_REV=	17123

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Numbered cases environment for LaTeX

CONFLICTS+=	ltx-misc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
