# $NetBSD$
# TeX Live Revision 17123

DISTNAME=	cases
PKGNAME=	tex-${DISTNAME}-2.5

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Numbered cases environment for LaTeX

CONFLICTS+=	ltx-misc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
