# $NetBSD: Makefile,v 1.2 2007/05/31 07:26:46 ghen Exp $

MOZILLA=		firefox
MOZ_VER=		1.5.0.12
MOZ_DISTVER=		${MOZ_VER}

HOMEPAGE=		http://www.mozilla.com/firefox/
COMMENT=		Lightweight gecko-based web browser (binary package)

DIST_SUBDIR=		${MOZILLA}/releases/${MOZ_DIR}

EMUL_PLATFORMS=		linux-i386
EMUL_PLATFORMS+=	solaris-i386 solaris-sparc

.include "../../www/seamonkey-bin/Makefile.common"
