# $NetBSD$
# TeX Live Revision 12163

DISTNAME=	amscls
PKGNAME=	tex-${DISTNAME}-2008.12163

MAINTAINER=	minskim@NetBSD.org
COMMENT=	AMS document classes for LaTeX

CONFLICTS+=	teTeX-texmf<=3.0nb18

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
