# $NetBSD$

DISTNAME=	sphack.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.0
TEXLIVE_REV=	20842

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-sphack

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
