# $NetBSD$
# FreeBSD Id: ports/misc/gone/Makefile,v 1.8 2001/01/16 17:31:40 sobomax Exp

DISTNAME=	gone-1.3.1
CATEGORIES=	misc
MASTER_SITES=	http://jaguar.ir.miami.edu/~marcus/

MAINTAINER=	zuntum@eik.pl
HOMEPAGE=	http://jaguar.ir.miami.edu/~marcus/

GNU_CONFIGURE=	yes
CONFIGURE_ENV=	with_setuid=no

.include "../../mk/bsd.pkg.mk"
