# $NetBSD: buildlink3.mk,v 1.7 2006/07/08 23:10:59 jlam Exp $

BUILDLINK_TREE+=	gsl

.if !defined(GSL_BUILDLINK3_MK)
GSL_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.gsl+=		gsl>=1.4
BUILDLINK_ABI_DEPENDS.gsl+=	gsl>=1.5nb1
BUILDLINK_PKGSRCDIR.gsl?=	../../math/gsl
.endif # GSL_BUILDLINK3_MK

BUILDLINK_TREE+=	-gsl
