# $NetBSD: Makefile,v 1.22 2005/09/30 12:31:28 wiz Exp $

DISTNAME=	gsl-1.7
CATEGORIES=	math devel
MASTER_SITES=	${MASTER_SITE_GNU:=gsl/}

MAINTAINER=	david@maxwell.net
HOMEPAGE=	http://www.gnu.org/software/gsl/gsl.html
COMMENT=	The GNU Scientific Library

GNU_CONFIGURE=		yes
USE_LIBTOOL=		yes
INFO_FILES=		gsl-ref.info

TEST_TARGET=		check

.include "../../mk/bsd.pkg.mk"
