# $NetBSD: Makefile,v 1.24 2006/03/31 23:56:28 jlam Exp $

DISTNAME=	gsl-1.8
CATEGORIES=	math devel
MASTER_SITES=	${MASTER_SITE_GNU:=gsl/}

MAINTAINER=	david@maxwell.net
HOMEPAGE=	http://www.gnu.org/software/gsl/gsl.html
COMMENT=	The GNU Scientific Library

USE_LIBTOOL=		yes
GNU_CONFIGURE=		yes
INFO_FILES=		# PLIST

TEST_TARGET=		check

.include "../../mk/bsd.pkg.mk"
