# $NetBSD: Makefile,v 1.6 1998/09/13 19:35:06 garbled Exp $
#

DISTNAME=	gnuplot-3.7
CATEGORIES=	graphics x11
MASTER_SITES=	ftp://ftp.gnuplot.vt.edu/pub/gnuplot/ \
		ftp://ftp.ucc.ie/pub/gnuplot/

MAINTAINER=	root@garbled.net
HOMEPAGE=	http://www.gnu.org/software/gnuplot/gnuplot.html

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
