# $NetBSD$
# TeX Live Revision 7340

DISTNAME=	type1cm.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.03

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-type1cm

CONFLICTS+=	teTeX-texmf<=3.0nb17

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
