# $NetBSD: Makefile.common,v 1.17 2003/07/17 21:39:59 grant Exp $

MESA_VERSION=		5.0.1
DISTNAME?=		MesaLib-${MESA_VERSION}
CATEGORIES?=		graphics
MASTER_SITES?= 		${MASTER_SITE_SOURCEFORGE:=mesa3d/}
EXTRACT_SUFX?=		.tar.bz2

MAINTAINER?=		tech-pkg@NetBSD.org
HOMEPAGE?=		http://www.mesa3d.org/

USE_GMAKE=		yes
USE_LIBTOOL=		yes
LIBTOOL_OVERRIDE=	${WRKSRC}/libtool

GNU_CONFIGURE?=		yes
CONFIGURE_ARGS+=	--enable-static

.include "../../mk/bsd.prefs.mk"
