# $NetBSD: Makefile.common,v 1.6 2003/03/09 19:04:52 jschauma Exp $

# Latest is:		5.0
# Default is:		5.0

MESA_VERSION=		${MESA_REQD}
DISTNAME?=		MesaLib-${MESA_VERSION}
CATEGORIES?=		graphics
MASTER_SITES?= 		${MASTER_SITE_SOURCEFORGE:=mesa3d/}
EXTRACT_SUFX?=		.tar.bz2

MAINTAINER?=		packages@netbsd.org
HOMEPAGE?=		http://www.mesa3d.org/

USE_GMAKE=		yes
USE_LIBTOOL=		yes
LTCONFIG_OVERRIDE=	${WRKSRC}/ltconfig

GNU_CONFIGURE?=		yes
CONFIGURE_ARGS+=	--enable-static
