# $NetBSD: Makefile,v 1.7 2004/01/31 16:47:26 grant Exp $

MOZILLA=	firefox

HOMEPAGE=	http://www.mozilla.org/projects/firefox/
COMMENT=	Lightweight gecko-based web browser (binary pkg)

ONLY_FOR_PLATFORM+=	Linux-*-i[3-6]86 NetBSD-*-i386

.include "../../www/mozilla-bin/Makefile.common"
