# $NetBSD$

PKGNAME=	postgresql84-${BASE_VERS}
COMMENT=	Robust, next generation, object-relational DBMS

DEPENDS+=	postgresql84-client>=${BASE_VERS}:../../databases/postgresql84-client
DEPENDS+=	postgresql84-server>=${BASE_VERS}:../../databases/postgresql84-server

META_PACKAGE=	yes

.include "Makefile.common"

.include "../../mk/bsd.pkg.mk"
