# $NetBSD: Makefile,v 1.2 2007/02/19 21:52:41 joerg Exp $

WBM_NAME=	cluster-webmin

COMMENT=	Webmin module to manage Webmin settings across a Webmin cluster

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
