# $NetBSD$

DISTNAME=	pst-barcode.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.08
TEXLIVE_REV=	21716

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-pst-barcode

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
