# $NetBSD$
# TeX Live Revision 15878

DISTNAME=	harvard
PKGNAME=	tex-${DISTNAME}-2.0.5

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Harvard citation package for use with LaTeX 2e

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
