# $NetBSD: Makefile,v 1.6 2008/04/04 15:19:57 jlam Exp $

DISTNAME=	daemons-1.1.0
CATEGORIES=	misc

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://daemons.rubyforge.org/
COMMENT=	Toolkit to convert Ruby scripts to a daemon
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
