# $NetBSD$

DISTNAME=	daemons-1.0.2
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	misc ruby
MASTER_SITES=	http://rubyforge.org/frs/download.php/13608/
EXTRACT_SUFX=	.tgz

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	http://daemons.rubyforge.org/
COMMENT=	Toolkit to convert Ruby scripts to a daemon

USE_RUBY_SETUP=	yes

.include "../../lang/ruby/modules.mk"
.include "../../mk/bsd.pkg.mk"
