# $NetBSD$

DISTNAME=	gkrellmoon-0.3
PKGNAME=	gkrellm-moon-0.3
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=gkrellmoon/}

MAINTAINER=	damon@netbsd.org
HOMEPAGE=	http://gkrellmoon.sourceforge.net/
COMMENT=	gkrellm moonclock plugin

DEPENDS+=       gkrellm-1.2.*:../../sysutils/gkrellm

.include "../../mk/bsd.pkg.mk"
