# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBMAD_BUILDLINK3_MK:=		${LIBMAD_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libmad
.endif

.if !empty(LIBMAD_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		libmad
BUILDLINK_DEPENDS.libmad+=	libmad>=0.15.0bnb1
BUILDLINK_PKGSRCDIR.libmad?=	../../audio/libmad
.endif	# LIBMAD_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
