# $NetBSD: Makefile,v 1.1.1.1 1999/03/11 20:17:36 bad Exp $

DISTNAME=	gnugo-2.0
CATEGORIES=	games
MASTER_SITES=	${MASTER_SITE_GNU:=gnugo/}

MAINTAINER=	bad@netbsd.org
HOMEPAGE=	http://www.gnu.org/software/gnugo/

do-configure:

.include "../../mk/bsd.pkg.mk"
