# $NetBSD$
# TeX Live Revision 11171

DISTNAME=	hyph-utf8.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2008.11171

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-hyph-utf8

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
