# $NetBSD$

DISTNAME=	subexec-0.0.4
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/nulayer/subexec
COMMENT=	Subexec spawns an external command with a timeout
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
