# $NetBSD: Makefile,v 1.15 2001/06/29 21:38:24 zuntum Exp $

DISTNAME=	mpeg_lib-1.3.1
PKGNAME=	mpeg-1.3.1
CATEGORIES=	graphics
MASTER_SITES=	ftp://ftp.mni.mcgill.ca/pub/mpeg/ \
		ftp://ftp.fu-berlin.de/unix/X11/graphics/gimp/libs/ \
		ftp://ftp.gimp.org/pub/gimp/libs/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://starship.python.net/~gward/mpeglib/
COMMENT=	Library for decoding MPEG movies

USE_BUILDLINK_ONLY=	# defined
USE_LIBTOOL=		# defined
GNU_CONFIGURE=		# defined
ALL_TARGET=		libmpeg_lib.la

.include "../../mk/bsd.pkg.mk"
