# $NetBSD$
# TeX Live Revision 15878

DISTNAME=	texpower
PKGNAME=	tex-${DISTNAME}-0.2

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Create dynamic online presentations with LaTeX

DEPENDS+=       tex-tpslifonts-[0-9]*:../../print/tex-tpslifonts

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
