# $NetBSD: Makefile,v 1.6 2006/06/02 13:48:11 joerg Exp $
#

DISTNAME=		nqc-2.3.r1
PKGNAME=		nqc-2.3.1
CATEGORIES=		devel
MASTER_SITES=		http://bricxcc.sourceforge.net/nqc/release/

MAINTAINER=		nathanw@NetBSD.org
HOMEPAGE=		http://bricxcc.sourceforge.net/nqc/
COMMENT=		Development system for the Lego Mindstorms RCX embedded computer

USE_LANGUAGES=		c++
USE_TOOLS+=		flex yacc

.include "../../mk/bsd.pkg.mk"
