# $NetBSD$

DISTNAME=	backports-2.7.1
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/marcandre/backports/
COMMENT=	Backports of Ruby features for older ruby
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
