# $NetBSD: Makefile,v 1.3 1999/07/31 19:02:03 rh Exp $
#

DISTNAME=	libxml-1.6.1
CATEGORIES=	textproc devel gnome
MASTER_SITES=	ftp://rpmfind.net/pub/veillard/ \
		${MASTER_SITE_GNOME:=sources/libxml/}

MAINTAINER=	rh@netbsd.org
HOMEPAGE=	http://rufus.w3.org/veillard/XML/xml.html

USE_LIBTOOL=	YES
GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
