# $NetBSD$

DISTNAME=	mhash-0.8.3
CATEGORIES=	security devel
MASTER_SITES=	http://mhash.sourceforge.net/dl/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://mhash.sourceforge.net/

USE_LIBTOOL=	yes
GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
