# $NetBSD$
# TeX Live Revision 15878

DISTNAME=	xcolor.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.11

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Documentation for tex-xcolor

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
