# $NetBSD: Makefile,v 1.1.1.1 2006/10/15 14:02:37 bouyer Exp $
#

DISTNAME=	dev86-0.16.17
CATEGORIES=	devel
MASTER_SITES=	http://homepage.ntlworld.com/robert.debath/dev86/
DISTFILES=	Dev86src-0.16.17.tar.gz

MAINTAINER=	pierrick@bs-network.net
HOMEPAGE=	http://www.swissgeeks.com/
COMMENT=	Linux 8086 development environment

MAKE_FLAGS+=	MANDIR=${PREFIX}/${PKGMANDIR}

.include "../../mk/bsd.pkg.mk"
