# $NetBSD: Makefile,v 1.4 1998/06/22 13:01:52 agc Exp $
#

DISTNAME=	wily-0.13.36
CATEGORIES=	plan9 editors
MASTER_SITES=	ftp://ftp.cs.su.oz.au/gary/wily/src/
EXTRACT_SUFX=	.tgz

MAINTAINER=	agc@netbsd.org
HOMEPAGE=	http://www.psrg.cs.usyd.edu.au/~gary/wily/

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
