# $NetBSD: Makefile,v 1.3 2003/01/19 09:04:02 salo Exp $

DISTNAME=	libdes-4.04b
WRKSRC=         ${WRKDIR}/des
CATEGORIES=	security
MASTER_SITES=   ftp://ftp.psy.uq.oz.au/pub/Crypto/DES/

MAINTAINER=	refling@comet.lbl.gov
COMMENT=	Small DES (Data Encryption Standard) lib & standalone program

CRYPTO=		YES

.include "../../mk/bsd.pkg.mk"
