# $NetBSD$
# TeX Live Revision 15878

DISTNAME=	subfigure
PKGNAME=	tex-${DISTNAME}-2.1.5

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Figures divided into subfigures (obsoleted by tex-subfig)

CONFLICTS+=	teTeX-texmf<=3.0nb19

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
