# $NetBSD$

DISTNAME=	c-ares-1.3.0
PKGNAME=	libcares-1.3.0
CATEGORIES=	net
MASTER_SITES=	http://daniel.haxx.se/projects/c-ares/

MAINTAINER=	adrianp@NetBSD.org
HOMEPAGE=	http://daniel.haxx.se/projects/c-ares/
COMMENT=	Asynchronous resolver library

GNU_CONFIGURE=	YES
USE_LIBTOOL=	YES

.include "../../mk/bsd.pkg.mk"
