# $NetBSD: Makefile,v 1.69 2004/02/09 07:54:58 minskim Exp $

.include "../../editors/xemacs/Makefile.common"

MAINTAINER=	uebayasi@NetBSD.org

USE_X11=	YES

.include "../../graphics/jpeg/buildlink2.mk"
.include "../../graphics/png/buildlink2.mk"
.include "../../graphics/tiff/buildlink2.mk"
.include "../../graphics/xpm/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
