# $NetBSD$

DISTNAME=	kdeartwork-2.2.2
COMMENT=	Art work for the KDE integrated X11 desktop

.include "../../x11/kde2/Makefile.kde2"

USE_BUILDLINK_ONLY=	YES

.include "../../mk/bsd.prefs.mk"

.include "../../x11/kde2/buildlink.mk"
.include "../../x11/kdebase2/buildlink.mk"
.include "../../mk/x11.buildlink.mk"
.include "../../mk/bsd.pkg.mk"
