# $NetBSD: Makefile,v 1.2 2002/03/27 09:41:27 skrll Exp $

DISTNAME=	kdeartwork-2.2.2
COMMENT=	Artwork for the KDE integrated X11 desktop

.include "../../x11/kde2/Makefile.kde2"

USE_BUILDLINK2=	YES

.include "../../x11/kde2/buildlink2.mk"
.include "../../x11/kdebase2/buildlink2.mk"

.include "../../mk/bsd.pkg.mk"
