#!/bin/sh
#
# $NetBSD: DEINSTALL,v 1.1.1.1 2002/08/06 14:04:34 wiz Exp $

PKGNAME=$1
STAGE=$2

XPDFRC=@PKG_SYSCONFDIR@/xpdfrc

case ${STAGE} in
DEINSTALL)
	;;

POST-DEINSTALL)
	@SED@ -e "/yrillic/d" ${XPDFRC} > ${XPDFRC}.tmp
	@MV@ -f ${XPDFRC}.tmp ${XPDFRC}
	;;

*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
exit 0
