# $NetBSD$
#

DISTNAME=		su2-1.3
CATEGORIES=		sysutils security
MASTER_SITES=		ftp://ftp.ccs.neu.edu/pub/sysadmin/

MAINTAINER=		collver@linuxfreemail.com
HOMEPAGE=		ftp://ftp.ccs.neu.edu/pub/sysadmin/
COMMENT=		enhanced su, users su with own password + more

LICENSE=		no-profit
NO_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
