# $NetBSD$

DISTNAME=	cns
PKGNAME=	tex-${DISTNAME}-2011
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	CNS fonts for CJK LaTeX

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
