# $NetBSD: Makefile,v 1.6 2003/09/21 09:21:07 jmc Exp $

DISTNAME=	dnspython-1.2.0
PKGNAME=	${PYPKGPREFIX}-dns-1.2.0
CATEGORIES=	net
MASTER_SITES=	http://www.dnspython.org/kits/${PKGVERSION}/

MAINTAINER=	gson@NetBSD.org
HOMEPAGE=	http://www.dnspython.org/
COMMENT=	Python DNS toolkit

PYDISTUTILSPKG=	yes
USE_BUILDLINK3=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
