# $NetBSD: Makefile,v 1.16 2008/04/25 20:39:11 joerg Exp $

DISTNAME=	dnspython-1.7.1
PKGNAME=	${PYPKGPREFIX}-dns-1.7.1
CATEGORIES=	net python
MASTER_SITES=	http://www.dnspython.org/kits/${PKGVERSION}/

MAINTAINER=	gson@NetBSD.org
HOMEPAGE=	http://www.dnspython.org/
COMMENT=	Python DNS toolkit
LICENSE=	modified-bsd

PKG_DESTDIR_SUPPORT=	user-destdir

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
