# $NetBSD$
# TeX Live Revision 17120

DISTNAME=	chbibref.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.0

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-chbibref

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
