# $NetBSD: Makefile,v 1.4 2001/08/22 17:39:00 jlam Exp $
#

DISTNAME=	ctwm-3.5.2
CATEGORIES=	x11 wm
MASTER_SITES=	http://ctwm.dl.nu/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://ctwm.dl.nu/
COMMENT=	Window manager with support for multiple virtual screens

USE_IMAKE=	YES

.include "../../graphics/xpm/buildlink.mk"
.include "../../mk/bsd.pkg.mk"
