# $NetBSD$

DISTNAME=	charter.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2010
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-charter

CONFLICTS+=	teTeX-texmf<=3.0nb29

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
