# $NetBSD: Makefile,v 1.7 2006/06/30 15:37:22 salo Exp $

DISTNAME=	suse_fontconfig-${SUSE_VERSION}
PKGREVISION=	3
CATEGORIES=	emulators

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Linux compatibility package for fontconfig

EMUL_MODULES.linux=	expat freetype2

.include "../../emulators/suse91_linux/Makefile.common"
.include "../../mk/bsd.pkg.mk"
