# $NetBSD: Makefile,v 1.9 2001/11/13 21:27:27 jlam Exp $

DISTNAME=	kdoc-2.2.2
CATEGORIES=	textproc kde
COMMENT=	C++ and IDL Class Documentation Tool

.include "../../x11/kde2/Makefile.kde2"

MAINTAINER=	wulf@netbsd.org

USE_BUILDLINK_ONLY=	YES
USE_PERL5=		YES

.include "../../mk/bsd.pkg.mk"
