# $NetBSD: Makefile,v 1.8 2001/10/18 09:57:11 skrll Exp $

DISTNAME=	kdoc-2.2.1
CATEGORIES=	textproc kde
MASTER_SITES=	ftp://ftp.kde.org/pub/kde/stable/2.2.1/src/ \
		ftp://ftp.us.kde.org/pub/kde/stable/2.2.1/src/ \
		ftp://ftp.de.kde.org/pub/kde/stable/2.2.1/src/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	wulf@netbsd.org
COMMENT=	C++ and IDL Class Documentation Tool

USE_PERL5=	YES
USE_GMAKE=	YES
GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
