# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
RSAREF_BUILDLINK3_MK:=	${RSAREF_BUILDLINK3_MK}+

.if !empty(RSAREF_BUILDLINK3_MK:M\+)
BUILDLINK_DEPENDS.rsaref?=	rsaref-2.0p3
BUILDLINK_PKGSRCDIR.rsaref?=	../../security/rsaref
.endif	# RSAREF_BUILDLINK3_MK

.if !empty(BUILDLINK_DEPTH:M\+)
BUILDLINK_DEPENDS+=	rsaref
.endif

.if !empty(RSAREF_BUILDLINK3_MK:M\+)
BUILDLINK_PACKAGES+=	rsaref
.endif	# RSAREF_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:C/\+$//}
