# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
MEANWHILE_BUILDLINK3_MK:=	${MEANWHILE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	meanwhile
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmeanwhile}
BUILDLINK_PACKAGES+=	meanwhile
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}meanwhile

.if ${MEANWHILE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.meanwhile+=	meanwhile>=1.0.2
BUILDLINK_PKGSRCDIR.meanwhile?=	../../chat/meanwhile
.endif	# MEANWHILE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
