# $NetBSD: Makefile,v 1.8 1999/09/20 09:30:18 agc Exp $
#

DISTNAME=		bladeenc-0.90-src-stable
PKGNAME=		bladeenc-0.90.0
CATEGORIES=		audio
MASTER_SITES=		http://bladeenc.mp3.no/source/

MAINTAINER=		packages@netbsd.org
HOMEPAGE=		http://bladeenc.mp3.no/

USE_GMAKE=		yes

WRKSRC=	${WRKDIR}/${PKGNAME}

GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
