# $NetBSD: Makefile,v 1.1.1.1 2009/06/07 07:07:51 minskim Exp $

DISTNAME=	rsfs
PKGNAME=	tex-${DISTNAME}-2009
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Ralph Smith's Formal Script font

CONFLICTS+=	teTeX-texmf<=3.0nb15

TEX_MIXEDMAP_FILES+=	rsfs.map

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
