# $NetBSD: Makefile,v 1.1.1.1 2010/04/11 20:49:55 minskim Exp $

DISTNAME=	breakcites
PKGNAME=	tex-${DISTNAME}-2010
TEXLIVE_REV=	21014

MAINTAINER=	minskim@NetBSD.org
COMMENT=	LaTeX package to a line break in multiple citations

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
