# $NetBSD: Makefile,v 1.9 2009/10/19 11:21:56 joerg Exp $
#

DISTNAME=		dulwich-0.4.0
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		devel python
MASTER_SITES=		http://samba.org/~jelmer/dulwich/

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://samba.org/~jelmer/dulwich/
COMMENT=		Python implementation of Git

PKG_DESTDIR_SUPPORT=	user-destdir

PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
