# $NetBSD$

DISTNAME=	fpl.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.002
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-fpl

CONFLICT=	teTeX-texmf<=3.0nb29

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
