# $NetBSD: Makefile,v 1.1.1.1 2010/04/28 16:21:10 minskim Exp $

DISTNAME=	needspace
PKGNAME=	tex-${DISTNAME}-1.3c
TEXLIVE_REV=	19684

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Insert pagebreak if not enough space

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
