# $NetBSD$
# TeX Live Revision 17999

DISTNAME=	needspace
PKGNAME=	tex-${DISTNAME}-1.3b

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Insert pagebreak if not enough space

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
