#!/bin/sh
#
#	$NetBSD$
#

# PROVIDE: pxe
# REQUIRE: DAEMON

. /etc/rc.subr

name="pxe"
command="@@PREFIX@@/sbin/${name}"
required_files="@@PREFIX@@/etc/${name}.conf"

load_rc_config $name
run_rc_command "$1"
