# $NetBSD$

MOZILLA=	seamonkey

COMMENT=	Full featured gecko-based browser (nightly binary pkg)

ONLY_FOR_PLATFORM+=	Linux-*-i[3-6]86 NetBSD-*-i386

.include "../../www/seamonkey-bin-nightly/Makefile.common"
