# $NetBSD: Makefile.SunOS.sparc,v 1.2 2007/02/22 19:01:27 wiz Exp $

SOLARIS_VERSION_REQD=	10

DISTNAME=	seamonkey-1.5a.en-US.solaris10-nosvg-i386
EXTRACT_SUFX=	.tar.bz2

MOZ_GTK2=	yes
MOZ_PLATFORM=	solaris
