# $NetBSD$
#

DISTNAME=	elfutils-0.152
CATEGORIES=	minix
MASTER_SITES=	https://fedorahosted.org/releases/e/l/elfutils/0.152/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	ben@minix3.org
HOMEPAGE=	https://fedorahosted.org/releases/e/l/elfutils/0.152/
COMMENT=	bsd licensed binutils
#LICENSE=	# TODO: (see mk/license.mk)

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=		yes
USE_PKGLOCALEDIR=	yes

.include "../../mk/bsd.pkg.mk"
