# $NetBSD$

DISTNAME=	ncntrsbk
PKGNAME=	tex-${DISTNAME}-2010
TEXLIVE_REV=	21570

MAINTAINER=	minskim@NetBSD.org
COMMENT=	New Century Scoolbook fonts

CONFLICTS=	teTeX-texmf<=3.0nb29

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
