# $NetBSD$
#

.include "Makefile.common"

CONFLICTS=		bittorrent-[0-9]*

PYDISTUTILSPKG=		yes

.include "../../lang/python/application.mk"
.include "../../lang/python/extension.mk"
.include "../../devel/py-cursespanel/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
