# $NetBSD$

R_PKGNAME=	mgcv
R_PKGVER=	0.8-1

MAINTAINER=	markd@netbsd.org
COMMENT=	Multiple smoothing parameter estimation and GAMs by GCV

PLIST_SRC=	/dev/null

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
