# $NetBSD$
# TeX Live Revision 9743

DISTNAME=	titlesec.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2.8

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-titlesec

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
