# $NetBSD: buildlink3.mk,v 1.3 2009/10/19 10:14:52 abs Exp $

BUILDLINK_TREE+=	p5-B-Utils

.if !defined(P5_B_UTILS_BUILDLINK3_MK)
P5_B_UTILS_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.p5-B-Utils+=	p5-B-Utils>=0.15nb1
BUILDLINK_PKGSRCDIR.p5-B-Utils?=	../../devel/p5-B-Utils
.endif # P5_B_UTILS_BUILDLINK3_MK

BUILDLINK_TREE+=	-p5-B-Utils
