# $NetBSD$
# TeX Live Revision 17358

DISTNAME=	hypernat
PKGNAME=	tex-${DISTNAME}-1.0b

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Allow hyperref and natbib to work together

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
