# $NetBSD$
# TeX Live Revision 7340

DISTNAME=	bibtex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.99c

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-bibtex

CONFLICTS+=	teTeX-texmf<=3.0nb15

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
