# $NetBSD: Makefile,v 1.9 2012/09/15 10:03:39 obache Exp $
#

GST_PLUGINS1_NAME=	twolame
GST_PLUGINS1_DIRS=	ext/twolame

.include "../../multimedia/gst-plugins1-ugly/Makefile.common"

.include "../../audio/twolame/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
