# $NetBSD$

DISTNAME=	Net_DIME-0.3
CATEGORIES+=	net

MAINTAINER=	jdolecek@NetBSD.org
HOMEPAGE= 	http://pear.php.net/package/Net_DIME
COMMENT=	PHP classes that implements DIME encoding

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
