# $NetBSD: Makefile,v 1.1.1.1 2008/07/19 18:23:46 ahoka Exp $

VERSION=	20020518
DISTNAME=	en_NZ
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	English (New Zealand) dictionary for hunspell

.include "../../textproc/hunspell/Makefile.common"

.include "../../mk/bsd.pkg.mk"
