#!/bin/sh
#
# $NetBSD$
#

PKGNAME=$1
STAGE=$2

PGHOME=@PGHOME@

case ${STAGE} in
DEINSTALL)
	;;
POST-DEINSTALL)
	cat << EOF
===========================================================================
If you won't be using ${PKGNAME} any longer, you may want to
remove the following directories:

	${PGHOME}
===========================================================================
EOF
	;;
*)
	echo "Unexpected argument: $2"
	exit 1
	;;
esac
exit 0
