# $NetBSD: Makefile,v 1.9 2012/09/15 10:03:38 obache Exp $
#

GST_PLUGINS1_NAME=	lame
GST_PLUGINS1_DIRS=	ext/lame

.include "../../multimedia/gst-plugins1-ugly/Makefile.common"

.include "../../audio/lame/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
