# $NetBSD: Makefile,v 1.2 2007/02/19 21:52:43 joerg Exp $

WBM_NAME=	postgresql

COMMENT=	Webmin module for managing PostgreSQL databases

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
