# $NetBSD: Makefile,v 1.4 2010/07/11 17:41:05 joerg Exp $

WBM_NAME=	postgresql

COMMENT=	Webmin module for managing PostgreSQL databases

.include "../../sysutils/webmin/wbm.mk"
.include "../../mk/bsd.pkg.mk"
