# $NetBSD: buildlink3.mk,v 1.2 2006/04/06 06:21:38 reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GPLCVER_BUILDLINK3_MK:=	${GPLCVER_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gplcver
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngplcver}
BUILDLINK_PACKAGES+=	gplcver

.if !empty(GPLCVER_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.gplcver+=	gplcver>=2.11a
BUILDLINK_PKGSRCDIR.gplcver?=	../../cad/gplcver
.endif	# GPLCVER_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
