# $NetBSD: Makefile.common,v 1.9 2005/01/23 20:41:48 recht Exp $
#

DISTNAME=	BitTorrent-4.0.1
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=bittorrent/}

MAINTAINER=	recht@NetBSD.org
HOMEPAGE=	http://www.bittorrent.com/
COMMENT=	File sharing tool

DISTINFO_FILE=	${.CURDIR}/../../net/bittorrent/distinfo
FILESDIR=	${.CURDIR}/../../net/bittorrent/files
PATCHDIR=	${.CURDIR}/../../net/bittorrent/patches

USE_BUILDLINK3=	YES

PYTHON_VERSIONS_ACCEPTED=	24 23 22
