# $NetBSD: Makefile,v 1.4 2003/06/02 01:15:57 jschauma Exp $

DISTNAME=	AbracadabraObject-1.5.1
PKGNAME=	zope25-AbracadabraObject-1.5.1
CATEGORIES=	www
MASTER_SITES=	http://www.zope.org/Members/mjablonski/AbracadabraObject/

MAINTAINER=	tech-pkg@netbsd.org
HOMEPAGE=	http://www.zope.org/Members/mjablonski/AbracadabraObject
COMMENT=	pre-configured objects with only one click

.include "../../www/zope25/product.mk"
.include "../../mk/bsd.pkg.mk"
