# $NetBSD: Makefile,v 1.18 2006/06/20 22:05:22 jlam Exp $

DISTNAME=	hanterm-3.1.6
PKGREVISION=	3
CATEGORIES=	x11 korean
MASTER_SITES=	http://download.kldp.net/hanterm/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://hanterm.kldp.net/
COMMENT=	X11R6-based xterm hacked for managing Korean languages

USE_IMAKE=	YES

.include "../../x11/libXaw/buildlink3.mk"
.include "../../x11/libXp/buildlink3.mk"
.include "../../x11/libXt/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
