# $NetBSD$
#

DISTNAME=		pyserial-2.6
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		comms python
MASTER_SITES=		http://pypi.python.org/packages/source/p/pyserial/

MAINTAINER=		tsarna@NetBSD.org
HOMEPAGE=		http://pyserial.sourceforge.net/
COMMENT=		Python Serial Port Extension
LICENSE=		python-software-foundation

USE_LANGUAGES=		#none

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
