# $NetBSD$
#

DISTNAME=	korfont
CATEGORIES=	fonts

DEPENDS+=	acroread-font-share-4.0:../../fonts/acroread-font-share

WRKSRC=		${WRKDIR}/KORKIT
TAR_FILE=	${WRKSRC}/LANGKOR.TAR

.include "../acroread-font-share/Makefile.common"
