# $NetBSD$
# TeX Live Revision 17157

DISTNAME=	chngcntr
PKGNAME=	tex-${DISTNAME}-1.0a

MAINTAINER=	minskim@NetBSD.org
COMMENT=	LaTeX package to change the resetting of counters

CONFLICTS+=	tex-ltxmisc<2009

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
