# $NetBSD: Makefile,v 1.2 2010/02/14 23:56:10 minskim Exp $

DISTNAME=	mflogo.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2009
PKGREVISION=	1
TEXLIVE_REV=	17487

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-mflogo

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
