# $NetBSD: Makefile,v 1.59 2012/04/10 10:53:28 wiz Exp $
#

PKGREVISION=	1

COMMENT=	Lynx-like text WWW browser

CONFLICTS+=	links-gui-[0-9]* elinks-0.3*

.include "../../www/links/Makefile.common"
.include "../../mk/bsd.pkg.mk"
