# $NetBSD$
# TeX Live Revision 15878

DISTNAME=	ifxetex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.5

MAINTAINER=	reed@reedmedia.net
HOMEPAGE=	http://tug.ctan.org/tex-archive/help/Catalogue/entries/ifxetex.html
COMMENT=	Documentation for tex-ifxetex

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
