# $NetBSD: Makefile,v 1.5 1998/07/15 15:21:54 hubertf Exp $

DISTNAME=	tgif-3.0-p16
PKGNAME=	tgif-3.0p16
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications/tgif

MAINTAINER=	mcmahill@alum.mit.edu
HOMEPAGE=	http://bourbon.cs.ucla.edu:8001/tgif/current.html

USE_IMAKE=	yes

.include "../../mk/bsd.pkg.mk"
