# $NetBSD: Makefile,v 1.1 1998/03/29 22:16:36 tron Exp $

DISTNAME=	tgif-3.0-p16
CATEGORIES=	graphics
MASTER_SITES=	${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications/tgif

MAINTAINER=	mcmahill@alum.mit.edu

USE_IMAKE=	yes

CAT1=	prtgif.0 tgif.0

.include "../../mk/bsd.pkg.mk"
