# $NetBSD: Makefile,v 1.24 2003/07/21 17:27:27 martti Exp $
#

.include "Makefile.common"

PKGREVISION=	1

CONFIGURE_ARGS+=	--disable-wordview
CONFIGURE_ENV+=		enable_wordview=no

.include "../../mk/bsd.pkg.mk"
