# $NetBSD$
# TeX Live Revision 17275

DISTNAME=	ftcap.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.4

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-ftcap

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
