# $NetBSD$

VERSION=	20060117
DISTNAME=	af_ZA
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Afrikaans dictionary for hunspell

.include "../../textproc/hunspell/Makefile.common"

.include "../../mk/bsd.pkg.mk"
