# $NetBSD: Makefile,v 1.2 1998/08/20 15:17:40 tsarna Exp $

DISTNAME=	xwrits-2.7.3
CATEGORIES=	x11
MASTER_SITES=	http://www.lcdf.org/~eddietwo/xwrits/

MAINTAINER=	mcmahill@alum.mit.edu
HOMEPAGE=	http://www.lcdf.org/~eddietwo/xwrits/

CONFLICTS=	xwrits-*

USE_X11=	YES
GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
