#!/bin/sh
#
# $NetBSD$

PKGNAME=$1
STAGE=$2

case ${STAGE} in
DEINSTALL)
	;;
POST-DEINSTALL)
	# Rebuild the ls-R database after removing files from the teTeX tree.
	#
	mktexlsr
	;;
*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
exit 0
