#!/bin/sh
#
# $NetBSD$

PKGNAME=$1
STAGE=$2

XPDFRC=${PKG_PREFIX}/etc/xpdfrc

case ${STAGE} in
DEINSTALL)
	;;

POST-DEINSTALL)
	sed -e "/implified/d" ${XPDFRC} > ${XPDFRC}.tmp
	sed -e "/gb2312/d" ${XPDFRC}.tmp > ${XPDFRC}
	rm -f ${XPDFRC}.tmp
	;;

*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
exit 0
