# $NetBSD$
# used by converters/nkf/Makefile
# used by converters/p5-nkf/Makefile

DISTNAME=	nkf-2.0.9
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE_JP:=nkf/37177/}

HOMEPAGE=	http://sourceforge.jp/projects/nkf/

DISTINFO_FILE=	${.CURDIR}/../../converters/nkf/distinfo
PATCHDIR=	${.CURDIR}/../../converters/nkf/patches
