# $NetBSD$

DISTNAME=		mgp-1.03a
CATEGORIES=		x11 graphics
MASTER_SITES=		ftp://ftp.mew.org/pub/MagicPoint/

MAINTAINER=		root@garbled.net
HOMEPAGE=		http://www.Mew.org/mgp/

GNU_CONFIGURE=		yes
USE_IMAKE=		yes

.include "../../mk/bsd.pkg.mk"
