# $NetBSD$
#

DISTNAME=	logging-0.4.7
PKGNAME=	${PYPKGPREFIX}-logging-0.4.7
CATEGORIES=	devel
MASTER_SITES=	http://www.red-dove.com/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.red-dove.com/python_logging.html
COMMENT=	Python logging system

USE_BUILDLINK2=	YES
PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
