# $NetBSD$

DISTNAME=	hike-1.2.1
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/sstephenson/hike
COMMENT=	Find files in a set of paths
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
