# $NetBSD: Makefile,v 1.2 2010/08/17 04:48:46 obache Exp $

DISTNAME=	roauth-0.0.3
CATEGORIES=	security

MAINTAINER=	obache@NetBSD.org
HOMEPAGE=	http://github.com/maccman/roauth
COMMENT=	Simple Ruby OAuth library
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
