# $NetBSD$

DISTNAME=	textcase.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-0.07
TEXLIVE_REV=	15878

MAINTAINER=	prlw1@cam.ac.uk
HOMEPAGE=	http://www.ctan.org/tex-archive/macros/latex/contrib/textcase/
COMMENT=	Documentation for tex-textcase
LICENSE=	lppl-1.3c

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
