# $NetBSD: Makefile,v 1.2 2010/04/15 23:02:08 minskim Exp $

DISTNAME=	babel.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-3.8l
TEXLIVE_REV=	20253

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-babel

CONFLICTS+=	teTeX-texmf<=3.0nb13

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
