# $NetBSD$
# TeX Live Revision 9808

DISTNAME=	babel.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-3.8l

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-babel

CONFLICTS+=	teTeX-texmf<=3.0nb13

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
