# $NetBSD$

DISTNAME=	marginnote
PKGNAME=	tex-${DISTNAME}-v1.1f
TEXLIVE_REV=	16624

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Notes in the margin, even where \marginpar fails

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
