#!/bin/sh
#
# $NetBSD$

case ${STAGE} in
POST-INSTALL)
	${RM} -f ${PKG_PREFIX}/include/pgsql
	${LN} -fs postgresql ${PKG_PREFIX}/include/pgsql
	;;

DEINSTALL)
	${RM} -f ${PKG_PREFIX}/include/pgsql
	;;
esac
