# $NetBSD: Makefile,v 1.140 2004/11/13 22:04:53 jlam Exp $

MOZILLA=	mozilla
MOZILLA_BIN=	mozilla-bin
MOZ_VER=	1.7.5
EXTRACT_SUFX=	.tar.bz2

DISTFILES=	${DISTNAME}${EXTRACT_SUFX}

COMMENT=	Full featured gecko-based browser

BUILD_SVG=	# defined
BUILD_MATHML=	# defined
BUILD_CALENDAR=	# defined

.include	"../../www/mozilla/Makefile.common"
