# $NetBSD: Makefile,v 1.2 1999/04/15 20:39:49 tron Exp $
#

DISTNAME=		xcb-2.3
CATEGORIES=		x11
MASTER_SITES=		${MASTER_SITE_XCONTRIB:=utilities/}

MAINTAINER=		root@garbled.net
COMMENT=		Extensible, multiple cut buffers for X

USE_IMAKE=		YES

.include "../../mk/bsd.pkg.mk"
