#!/bin/sh
#
# $NetBSD: arlad,v 1.1 2001/08/09 13:48:59 wennmach Exp $
#
# PROVIDE: arlad
# REQUIRE: beforemountlkm

if [ -f /etc/rc.subr ]; then
	. /etc/rc.subr
fi

name="arlad"
rcvar=$name
command="@PREFIX@/libexec/${name}"
command_args="-z /dev/xfs0"
required_files="/dev/xfs0"

if [ -f /etc/rc.subr -a -d /etc/rc.d -a -f /etc/rc.d/DAEMON ]; then
	load_rc_config $name
	run_rc_command "$1"
else
	echo -n ' ${name}'
	${command} ${arlad_flags} ${command_args}
fi
