# $NetBSD: Makefile,v 1.19 2004/12/04 03:50:40 taya Exp $

MOZILLA=	mozilla-stable
MOZILLA_BIN=	mozilla-bin
MOZ_VER=	1.7.5
EXTRACT_SUFX=	.tar.bz2

DISTFILES=      ${DISTNAME}${EXTRACT_SUFX}

COMMENT=	Full featured gecko-based browser (stable branch)

BUILD_SVG=	# defined
BUILD_MATHML=	# defined
BUILD_CALENDAR=	# defined

.include	"../../www/mozilla/Makefile.common"
