# $NetBSD: Makefile,v 1.3 2010/05/10 05:59:58 minskim Exp $

DISTNAME=	misc
PKGNAME=	tex-${DISTNAME}-2010
TEXLIVE_REV=	17497

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Miscellaneous files for TeX

CONFLICTS+=	teTeX-texmf<=3.0nb11

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
