# $NetBSD: Makefile,v 1.1.1.1 2009/04/13 07:12:05 minskim Exp $
# TeX Live Revision 15878

DISTNAME=	misc
PKGNAME=	tex-${DISTNAME}-2009.15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Miscellaneous files for TeX

CONFLICTS+=	teTeX-texmf<=3.0nb11

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
