# $NetBSD: Makefile,v 1.14 2007/05/05 22:09:19 adrianp Exp $

DISTNAME=	HTML_Common-1.2.3
PKGREVISION=	1
CATEGORIES=	www

MAINTAINER=	jdolecek@NetBSD.org
COMMENT=	Base PHP class for other HTML classes

PKG_DESTDIR_SUPPORT=	user-destdir

CONFLICTS=	php-pear-HTML_Common-[0-9]*

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
