# $NetBSD$
#

DISTNAME=	Fortune-0.5.2
PKGNAME=	zope25-Fortune-0.5.2
CATEGORIES=	www
MASTER_SITES=	http://www.zope.org/Members/lalo/Fortune/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.zope.org/Members/lalo/Fortune
COMMENT=	randomly-selected fortune cookie

ZOPE_COPYPRODUCT= zope-std-copyproduct-long

.include "../../www/zope25/product.mk"
.include "../../mk/bsd.pkg.mk"
