# $NetBSD$
#

DISTNAME=		diffstat-1.33
CATEGORIES=		textproc
MASTER_SITES=		ftp://invisible-island.net/diffstat/
EXTRACT_SUFX=		.tgz

MAINTAINER=		packages@netbsd.org
HOMEPAGE=		http://dickey.his.com/diffstat/diffstat.html
COMMENT=		display a histogram of diff changes

#USE_BUILDLINK2=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

MAKEFILE=		makefile

.include "../../mk/bsd.pkg.mk"
