# $NetBSD$
# TeX Live Revision 16881

DISTNAME=	enctex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2009

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-enctex

CONFLICTS+=	teTeX-texmf<=3.0nb15

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
