# $NetBSD: Makefile,v 1.3 2003/07/17 22:55:55 grant Exp $

DISTNAME= 		MozillaFirebird-bin-acroread3-1.0

MAINTAINER=		kei@NetBSD.org
COMMENT=		Acrobat Reader 3 plugin for phoenix-bin

DEPENDS+=		acroread5-5.[0-9]*:../../print/acroread
CONFLICTS+=		phoenix-bin-acroread-[0-9]*
CONFLICTS+=		phoenix-bin-acroread5-[0-9]*
CONFLICTS+=		MozillaFirebird-bin-acroread-[0-9]*
CONFLICTS+=		MozillaFirebird-bin-acroread5-[0-9]*

ACROREAD=		Acrobat3

.include "../../www/MozillaFirebird-bin-acroread/Makefile.common"
