# $NetBSD$
#

DISTNAME=	libradius-linux-20040827
CATEGORIES=	net
MASTER_SITES=	http://portal-to-web.de/tacacs/

MAINTAINER=	manu@netbsd.org
COMMENT=	RADIUS client library

WRKSRC=		${WRKDIR}/libradius-linux

.include "../../mk/bsd.pkg.mk"
