# $NetBSD: Makefile,v 1.1.1.1 2009/07/15 23:54:10 minskim Exp $

DISTNAME=	courier
PKGNAME=	tex-${DISTNAME}-2009
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Adobe Type 1 "free" copies of Courier

CONFLICTS+=	teTeX-texmf<=3.0nb19

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
