# $NetBSD$
# TeX Live Revision 7340

DISTNAME=	sttools
PKGNAME=	tex-${DISTNAME}-2008.7340

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Various LaTeX tools and macros

.include "../../print/texlive/module.mk"
.include "../../mk/bsd.pkg.mk"
