# $NetBSD: Makefile,v 1.3 2011/05/10 13:28:38 taca Exp $

DISTNAME=	arel-2.0.10
CATEGORIES=	databases

# Note: databases/ruby-activerecord3 requires ruby-arel<2.1.
MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/brynary/arel/
COMMENT=	Arel is a relational algebra engine for Ruby
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
