# $NetBSD: Makefile,v 1.2 2005/04/11 21:45:14 tv Exp $

MODNAME=		dbx
PECL_VERSION=		1.1.0
CATEGORIES+=		databases
PKGREVISION=		# empty
COMMENT=		PHP database abstraction layer extension

MAINTAINER=		jdolecek@NetBSD.org


.include "../../lang/php/ext.mk"
.include "../../mk/bsd.pkg.mk"
