# $NetBSD: Makefile,v 1.3 2004/11/05 17:11:39 jdolecek Exp $

MODNAME=		dbx
CATEGORIES+=		databases
PKGREVISION=		# empty
COMMENT=		PHP database abstraction layer extension

MAINTAINER=		jdolecek@NetBSD.org

USE_BUILDLINK3=		yes

.include "../../lang/php/ext.mk"
.include "../../mk/bsd.pkg.mk"
