# $NetBSD$

DISTNAME=	xetexconfig
PKGNAME=	tex-${DISTNAME}-2010
TEXLIVE_REV=	18937

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Configuration files for XeTeX

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
