# $NetBSD$

DISTNAME=	bchunk-1.0.0
CATEGORIES=	sysutils
MASTER_SITES=	http://hes.iki.fi/bchunk/

MAINTAINER=	pooka@netbsd.org
HOMEPAGE=	http://hes.iki.fi/bchunk/

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/bchunk ${PREFIX}/bin/bchunk

.include "../../mk/bsd.pkg.mk"
