# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
P5_NET_SNMP_BUILDLINK3_MK:=	${P5_NET_SNMP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	p5-Net-SNMP
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Np5-Net-SNMP}
BUILDLINK_PACKAGES+=	p5-Net-SNMP

.if !empty(P5_NET_SNMP_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.p5-Net-SNMP+=	p5-Net-SNMP>=5.0.1nb1
BUILDLINK_PKGSRCDIR.p5-Net-SNMP?=	../../net/p5-Net-SNMP
.endif	# P5_NET_SNMP_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
