# $NetBSD$

DISTNAME=	supertabular.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-4.1a
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-supertabular

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
