# $NetBSD$
# TeX Live Revision 17039

DISTNAME=	german
PKGNAME=	tex-${DISTNAME}-2.5e

MAINTAINER=	tron@NetBSD.org
COMMENT=	LaTeX styles for German typography

CONFLICTS+=	teTeX-texmfsrc-[0-9]*

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
