# $NetBSD: Makefile,v 1.33 2003/03/26 04:05:40 jschauma Exp $
#

COMMENT=	Netscape Communicator browser, version 4 (binary pkg)

BINNAME=	communicator
DIST_SDIR_NAME=	complete_install

.include "../navigator/Makefile.common"
.include "../../mk/bsd.pkg.mk"
