# $NetBSD: Makefile,v 1.9 1999/06/14 01:41:34 hubertf Exp $

DISTNAME=		polclock-1.11
CATEGORIES=		x11
MASTER_SITES=		http://www.daionet.gr.jp/~masa/archives/

MAINTAINER=		packages@netbsd.org
HOMEPAGE=		http://www.daionet.gr.jp/~masa/glclock

USE_X11BASE=		yes
USE_IMAKE=		yes

.include "../../mk/bsd.pkg.mk"
