# $NetBSD: Makefile,v 1.3 2010/09/10 08:08:14 taca Exp $

DISTNAME=	fastercsv-1.5.4
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://fastercsv.rubyforge.org/
COMMENT=	Replacement to Ruby standard CSV library
LICENSE=	gnu-gpl-v2 OR ruby-license

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
