# $NetBSD: Makefile,v 1.1.1.1 2009/04/29 05:49:33 minskim Exp $

DISTNAME=	fancyhdr.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-3.1
TEXLIVE_REV=	15878

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-fancyhdr

CONFLICTS+=	teTeX-texmf<=3.0nb13

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
