# $NetBSD$
#

GST_PLUGINS_NAME=	theora
GST_PLUGINS_DIR=	ext/theora

.include "../../multimedia/gst-plugins/Makefile.common"

.include "../../multimedia/libtheora/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
